"""Neo4j client — backward-compat re-export shim.

All implementations have moved to the neo4j/ subpackage.
Import from here (existing callers) or directly from neo4j/ submodules.
"""

from app.services.agents.neo4j import (
    init_neo4j,
    close_neo4j,
    get_driver,
    _neo4j_run,
    _neo4j_run_single,
    _neo4j_write,
    # table search
    search_tables_vector,
    search_tables_fulltext,
    search_tables_via_intents,
    search_tables_via_community,
    search_tables_via_domain,
    search_tables_via_joinpaths,
    search_tables_via_business_terms,
    search_tables_via_columns,
    search_tables_from_query_patterns,
    search_tables_via_filter_values,
    get_tables_with_context,
    get_table_relevant_intents,
    get_structurally_similar_tables,
    get_community_bridges,
    get_business_term_table_edges,
    search_tables_via_query_templates,
    get_business_terms_with_related_tables,
    # column search
    search_columns_vector,
    search_columns_fulltext,
    get_columns_for_tables,
    get_columns_by_ids,
    get_join_critical_columns,
    get_semantically_similar_columns,
    resolve_columns,
    find_join_by_value_overlap,
    # join resolution
    load_join_path,
    load_join_path_yens,
    load_best_join_path,
    get_direct_joins,
    get_join_paths_by_ids,
    get_joinpath_joins,
    get_all_join_paths_for_tables,
    find_join_via_graph_traversal,
    # hub detection
    get_dimension_hub_for_communities,
    find_common_dimension_hub,
    # template / pattern / intent / term search
    search_query_templates,
    search_query_templates_fulltext,
    search_query_patterns,
    search_anti_patterns,
    search_intents,
    search_business_terms_vector,
    search_business_terms_fulltext,
    lookup_business_terms,
    get_query_templates_by_ids,
    get_query_patterns_by_ids,
    get_anti_patterns_by_ids,
    get_business_terms_by_terms,
    get_business_terms_for_tables,
    get_all_domain_names,
    get_all_intent_names,
    get_tables_for_canonical_domains,
    # write
    write_join_path,
    write_query_pattern,
    write_anti_pattern,
    update_pattern_feedback,
    promote_pattern_to_template,
    write_schema_gap,
)

# Legacy aliases that existed before the refactor
search_tables_via_templates_vector = None   # removed — templates no longer drive table selection
search_tables_via_templates_fulltext = None  # removed — templates no longer drive table selection

__all__ = [
    "init_neo4j", "close_neo4j",
    "search_tables_vector", "search_tables_fulltext",
    "search_tables_via_intents", "search_tables_via_community",
    "search_tables_via_domain", "search_tables_via_joinpaths",
    "search_tables_via_business_terms", "search_tables_via_columns",
    "search_tables_from_query_patterns", "search_tables_via_filter_values",
    "get_tables_with_context", "get_table_relevant_intents",
    "get_structurally_similar_tables", "get_community_bridges", "get_business_term_table_edges",
    "search_tables_via_query_templates", "get_business_terms_with_related_tables",
    "search_columns_vector", "search_columns_fulltext",
    "get_columns_for_tables", "get_columns_by_ids", "get_join_critical_columns",
    "get_semantically_similar_columns", "resolve_columns", "find_join_by_value_overlap",
    "load_join_path", "load_join_path_yens",
    "load_best_join_path", "get_direct_joins",
    "get_join_paths_by_ids", "get_joinpath_joins",
    "get_all_join_paths_for_tables", "find_join_via_graph_traversal",
    "get_dimension_hub_for_communities", "find_common_dimension_hub",
    "search_query_templates", "search_query_templates_fulltext",
    "search_query_patterns",
    "search_anti_patterns", "search_intents",
    "search_business_terms_vector", "search_business_terms_fulltext",
    "lookup_business_terms",
    "get_query_templates_by_ids", "get_query_patterns_by_ids",
    "get_anti_patterns_by_ids", "get_business_terms_by_terms", "get_business_terms_for_tables",
    "get_all_domain_names", "get_all_intent_names", "get_tables_for_canonical_domains",
    "write_join_path", "write_query_pattern", "write_anti_pattern",
    "update_pattern_feedback", "promote_pattern_to_template", "write_schema_gap",
]
