"""AnalyticsState TypedDict for the Neo4j analytics LangGraph pipeline.

A single AnalyticsState carries all fields for the 13-node pipeline.
Nodes only populate the fields they produce; unset fields remain at defaults.
"""

from __future__ import annotations

import operator
from typing import Annotated


def _specialist_outputs_reducer(existing: list, update: list) -> list:
    """Append-or-reset reducer for specialist_outputs.

    If update[0] == {"__reset__": True}, clears the list (stale cross-turn state fix).
    Otherwise appends — standard LangGraph Send accumulation for parallel specialists.
    """
    if update and isinstance(update[0], dict) and update[0].get("__reset__"):
        return list(update[1:])
    return (existing or []) + (update or [])

from langgraph.graph.message import add_messages
from typing_extensions import TypedDict


class AnalyticsState(TypedDict):
    # ── Core conversation ────────────────────────────────────────────────────
    messages: Annotated[list, add_messages]
    conversation_history: str             # pre-formatted "User: ...\nAssistant: ..." from DB (bypasses checkpoint messages for LLM context)
    user_id: str
    thread_id: str
    persona: str                          # executive | analyst | manager — passed in from HTTP, NOT re-detected
    question: str
    effective_question: str             # full reconstructed intent: = question for normal, prior+current for refinements/follow-ups

    # ── Routing ──────────────────────────────────────────────────────────────
    question_type: str                    # general_chat | analytics
    is_followup: bool                     # True when question semantically continues a prior analytics answer
    complexity: str | None               # simple | complex | advanced — set by intake_classifier LLM
    query_type: str | None               # lookup | aggregate | trend | comparison | ratio — set by intake_classifier from query_intent signals
    entity_tokens: list[str] | None       # proper nouns / named entities extracted by intake_classifier LLM (e.g. ["JPMorgan", "operating account"])
    needs_clarification: bool
    clarification_count: int              # max 2 per turn
    clarification_reason: str | None

    # ── Pipeline ─────────────────────────────────────────────────────────────
    semantic_context: dict | None         # output of context_fetcher (Phase 1: tables + Group A, no columns)
    query_plan: dict | None               # output of anchor_resolver (merged) — user's explicit output spec (cols, groupings, time, entities, complexity)
    enriched_schema: dict | None          # output of schema_enricher — complete columns for anchor_tables only
    anchor_tables_resolved: list[str]     # output of anchor_resolver — 2-4 anchor tables before ir_builder
    anchor_join_paths: list[dict] | None  # confirmed join paths between anchor tables (JOINS_TO + JoinPath)
    candidate_overlap_joins: list[dict] | None  # heuristic value-overlap joins — only used when no structural path exists
    fx_rate_template_join: bool | None    # set by anchor_resolver when lpp.fx_rate is injected via fx_required — signals schema_enricher to skip structural path for fx_rate
    llm_selected_anchors: list[str] | None  # tables the LLM explicitly selected (before signal injection) — exempt from cascade_prune
    fan_out_annotated_fqns: list[str] | None  # tables whose join paths are annotated pre_agg_required — sql_generator must not direct-JOIN these
    neo4j_raw_graph: dict | None          # accumulated raw Neo4j nodes/edges from all pipeline stages (for trust visualization)
    search_terms: list[str] | None      # 3 focused keyword phrases generated by intake_classifier for multi-term Neo4j discovery
    search_variants: list[str] | None   # corrected/expanded entity tokens (abbrev expansions + typo fixes) replacing raw entity_tokens downstream
    query_intent: list[str] | None      # typed intent lines from intake_classifier: GOAL/TIME/COMPARISON/DOMAIN/CONDITION/SCENARIO/CONTEXT/OUTPUT
    concept_mappings: dict | None         # BusinessTerm → {definition, computation} for anchor tables
    specialist_outputs: Annotated[list[dict], _specialist_outputs_reducer]  # accumulates from 3 parallel specialists via Send; reset each turn by intake_classifier
    resolved_intent: dict | None          # output of intent_assembler (same format as old intent_resolver)
    intent_directive: str | None              # raw directive from intent_resolver <directive> tag
    intent_directive_instructions: str | None  # <instructions> sub-section: SQL execution requirements
    intent_directive_context: str | None       # <context> sub-section: structural guidance, informational
    filter_directive: str | None          # resolved filter list from filter_resolver (DB codes + confidence)
    filter_directive_hint: str | None     # filter specialist reasoning (user term → DB value mappings)
    schema_directive: str | None          # code-verified structure from ir_builder (tables, joins, measures) — passed to sql_generator + repair
    semantic_ir_list: list[dict]          # list of SemanticIR (always 1 — decomposition removed)
    sql_list: list[str]                   # compiled SQL (always 1 entry)
    recompile_count: int                  # max 1
    repair_count: int                     # max 2 across all repair types
    filter_resolution_needed: bool
    repair_history: list[dict]            # [{attempt, error, sql_fingerprint|sql_fragment}] — prevents circular repair

    early_filter_spec: dict | None          # L4: entity-first CTE blueprint for deep-join queries (join_depth > 2)


    # ── Execution ────────────────────────────────────────────────────────────
    result_list: list[dict]               # raw query results per sub-query
    query_summary: dict | None            # QuerySummary object
    result_was_truncated: bool            # True if any sub-query result exceeded the row cap
    no_data: bool
    reliability_flags: list[str]
    low_confidence_filters: list[dict]
    zero_row_probe_result: str | None     # human-readable explanation from Z2/Z3 probe
    zero_row_rewrite_count: int           # tracks zero-row repair attempts (max 1) to prevent infinite loops
    zero_row_probe_type: str | None       # probe_type from zero_row_probe (e.g. "filter_mismatch") — used for AntiPattern write

    # ── Data quality (pre-synthesis gate) ────────────────────────────────────
    data_quality_flag: bool               # True if DATA_INTEGRITY_GATE triggered by data_quality_checker
    data_quality_reason: str | None       # One-sentence reason from data_quality_checker (shown as #### Data Quality Concern)

    # ── Output ───────────────────────────────────────────────────────────────
    answer: str
    chart_spec: dict | None
    chart_type: str | None
    alternative_chart_specs: list[dict]    # full Vega-Lite specs — each: {"chart_type": str, "spec": dict}
    follow_ups: list[str]

    # ── Memory / feedback ────────────────────────────────────────────────────
    feedback_context: list               # list[dict] of merged thread+similar feedback rows; nodes call build_feedback_context_for_node() to filter by type
    lt_memory_context: str               # long-term memory fetched by lt_memory_retriever node
    preference_summary: dict | None      # structured summary from lt_memory_retriever (counts + items) → saved to message metadata
    preference_label: str | None         # markdown summary for UI pipeline step
    global_instructions: str             # enabled user standing instructions loaded pre-pipeline; injected into synthesis/general_chat/sql_generator etc.
    distilled_preferences: str           # Haiku-synthesised 5-8 bullet behavioural profile; injected instead of raw feedback when fresh (set by chat.py pre-load)
    intent_fingerprint: dict | None      # {anchor_tables, measures, filters, dimensions, time_period} — built by directive_writer; stored to message metadata for feedback FTS
    summary: str                          # short-term session summary
    context_fetch_label: str | None      # deterministic markdown summary from context_fetcher — emitted as synthetic reasoning.delta

    # ── Error / control ──────────────────────────────────────────────────────
    error: str | None
    execution_error: str | None          # DB-level error surfaced by executor; fed to intent_resolver for semantic re-interpretation
    _prev_repair_count: int              # last repair_count at executor completion; detects new repairs in route_executor
    stopped: bool
    deep_analysis: bool
    tribal_facts: list[dict]
    max_rows: int                         # user-configured SQL row limit (default 100, applied as LIMIT in executor)

    # ── Deep analysis supplementary outputs ──────────────────────────────────
    sensitivity_table: list[dict] | None    # threshold sensitivity: [{threshold, count, total}] from deep_sensitivity node
    denominator_context: dict | None        # natural denominator: {concept, value, share} from deep_denominator node
    temporal_projection: dict | None        # in-flight projection: {completeness_pct, projected_total, prior_period_at_same_point, prior_period_final} from deep_projection node

    # ── Audit / lineage ───────────────────────────────────────────────────────
    user_email: str | None               # caller email — written to execution log
    pipeline_start_ms: float             # time.perf_counter() at pipeline entry — used to compute duration_ms in audit log
    current_date: str                    # ISO date (YYYY-MM-DD) at pipeline start — synthesis uses this for temporal calculations
    pattern_matched: bool                # set True by query_compiler when a QueryPattern is found and used
    pattern_name: str | None             # intent of the top matched pattern
    is_retry: bool                       # True when triggered from /retry or /edit endpoint
    prior_sql: str | None               # SQL from the immediately prior pipeline run; set by sql_generator; used by intent_resolver and sql_generator on retry/error
    prior_question: str | None          # original question text looked up from DB; used by context_fetcher to find the right tables for refinements
    prior_sql_tables: list[str]         # schema.table FQNs parsed from prior_sql (e.g. ["lpp.counterparty_exposure"])
    is_refinement: bool                 # True for user-initiated refinements (prior_sql from frontend, not is_retry)
    prior_execution_context: dict | None  # structured context from the last analytics turn (read from DB); passed to specialists as non-directive reference
    prior_context_window: list[dict] | None  # last N analytics turns' structured context (newest first, no SQL); rolling thread-context window passed to specialists
    prior_output_columns: list[str]      # actual result column names from the most recent prior analytics query; injected into query_planner for continuation column continuity

    # ── sql_generator intra-turn cache (avoids redundant Neo4j calls on recompile) ──
    _sql_schema_ctx_cache: dict | None  # result of build_schema_context — reused on recompile
    _cached_anti_patterns: str | None   # pre-formatted anti-pattern text — reused on recompile
    _cached_query_patterns: list | None # raw query pattern list — reused on recompile

    # ── Track B: QueryPattern intent re-ranking ──────────────────────────────
    _refined_matched_pattern: dict | None  # Pass 2 pattern from anchor_resolver (intent-aware re-search); beats Pass 1 when raw_score > threshold
    _refined_feedback_pool: list           # Pass 2 feedback from anchor_resolver (intent-aware re-rank of similar feedback)
    pattern_cache_hit: bool                # True when sql_generator bypassed LLM and returned cached SQL from QueryPattern node

    # ── specialist <output> captures (written by each specialist; read by audit to persist) ──
    # Annotated reducer: keep first non-empty value — survives parallel Send API branch merges
    _measure_specialist_output:   Annotated[str | None, lambda a, b: b if b else a]
    _dimension_specialist_output: Annotated[str | None, lambda a, b: b if b else a]
    _directive_summary:           Annotated[str | None, lambda a, b: b if b else a]
    _cte_outline:                 Annotated[str | None, lambda a, b: b if b else a]
