"""add refresh token

Revision ID: 8caf9ba89794
Revises: 0019_disable_seeded_passwords
Create Date: 2026-07-13 12:58:52.224778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8caf9ba89794'
down_revision: Union[str, Sequence[str], None] = '0019_disable_seeded_passwords'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mti_brain_refresh_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['mti_brain_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_token_hash', 'mti_brain_refresh_token', ['token_hash'], unique=False)
    op.create_index('ix_refresh_token_user', 'mti_brain_refresh_token', ['user_id'], unique=False)
    op.drop_index(op.f('ix_mti_brain_dashboard_conversation'), table_name='mti_brain_dashboard')
    op.create_index('ix_mti_brain_dashboard_conversation', 'mti_brain_dashboard', ['conversation_id'], unique=False)
    op.drop_column('mti_brain_feedback', 'verified_for_hil')
    op.drop_index(op.f('ix_mti_brain_graph_context_conversation'), table_name='mti_brain_graph_context')
    op.create_index('ix_mti_brain_graph_context_conversation', 'mti_brain_graph_context', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mti_brain_graph_context_conversation', table_name='mti_brain_graph_context')
    op.create_index(op.f('ix_mti_brain_graph_context_conversation'), 'mti_brain_graph_context', ['conversation_id'], unique=True)
    op.add_column('mti_brain_feedback', sa.Column('verified_for_hil', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index('ix_mti_brain_dashboard_conversation', table_name='mti_brain_dashboard')
    op.create_index(op.f('ix_mti_brain_dashboard_conversation'), 'mti_brain_dashboard', ['conversation_id'], unique=True)
    op.drop_index('ix_refresh_token_user', table_name='mti_brain_refresh_token')
    op.drop_index('ix_refresh_token_hash', table_name='mti_brain_refresh_token')
    op.drop_table('mti_brain_refresh_token')
    # ### end Alembic commands ###
