graph TD;
	__start__([<p>__start__</p>]):::first
	intake_classifier(intake_classifier)
	general_chat(general_chat)
	context_fetcher(context_fetcher)
	tribal_retrieval(tribal_retrieval)
	anchor_resolver(anchor_resolver)
	query_planner(query_planner)
	schema_enricher(schema_enricher)
	measure_specialist(measure_specialist)
	filter_specialist(filter_specialist)
	dimension_specialist(dimension_specialist)
	intent_assembler(intent_assembler<hr/><small><em>defer = True</em></small>)
	directive_writer(directive_writer)
	schema_gap_resolver(schema_gap_resolver)
	intent_resolver(intent_resolver)
	query_compiler(query_compiler)
	filter_resolver(filter_resolver)
	sql_generator(sql_generator)
	sql_validator(sql_validator)
	executor(executor)
	data_quality_checker(data_quality_checker)
	deep_sensitivity(deep_sensitivity)
	deep_denominator(deep_denominator)
	deep_projection(deep_projection)
	synthesis(synthesis)
	chart_agent(chart_agent)
	error_response(error_response)
	compress(compress)
	__end__([<p>__end__</p>]):::last
	__start__ --> intake_classifier;
	anchor_resolver -.-> intent_resolver;
	anchor_resolver -.-> query_planner;
	chart_agent -.-> __end__;
	chart_agent -.-> compress;
	compress -.-> intent_assembler;
	context_fetcher -.-> error_response;
	context_fetcher -. &nbsp;anchor_resolver&nbsp; .-> tribal_retrieval;
	data_quality_checker --> deep_sensitivity;
	deep_denominator --> deep_projection;
	deep_projection --> synthesis;
	deep_sensitivity --> deep_denominator;
	dimension_specialist --> intent_assembler;
	directive_writer --> schema_gap_resolver;
	error_response -.-> __end__;
	error_response -.-> compress;
	executor -.-> data_quality_checker;
	executor -.-> deep_sensitivity;
	executor -.-> intent_resolver;
	executor -.-> sql_validator;
	filter_resolver -.-> sql_generator;
	filter_specialist --> intent_assembler;
	general_chat -.-> __end__;
	general_chat -.-> compress;
	intake_classifier -.-> context_fetcher;
	intake_classifier -.-> general_chat;
	intent_assembler -.-> directive_writer;
	intent_assembler -.-> intent_resolver;
	intent_resolver --> query_compiler;
	measure_specialist --> intent_assembler;
	query_compiler -.-> error_response;
	query_compiler -.-> filter_resolver;
	query_compiler -.-> sql_generator;
	query_planner --> schema_enricher;
	schema_enricher --> dimension_specialist;
	schema_enricher --> filter_specialist;
	schema_enricher --> measure_specialist;
	schema_gap_resolver --> query_compiler;
	sql_generator --> sql_validator;
	sql_validator -.-> error_response;
	sql_validator -.-> executor;
	sql_validator -.-> sql_generator;
	synthesis -.-> __end__;
	synthesis -.-> chart_agent;
	synthesis -.-> compress;
	tribal_retrieval --> anchor_resolver;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc