"""Node 5: chart_agent — selects chart type and generates Vega-Lite labels.

Step 1: LLM selects chart type AND generates labels in one call (semantic, persona-aware).
        LLM receives column descriptions from Neo4j — knows if a column is USD, count, ratio, etc.
Step 2: Hard safety guardrails applied after LLM choice (single row → kpi_card, etc.).
Step 3: Programmatic Vega-Lite spec builder injects fixed fields and data rows.
Step 4: Post-processor — humanize labels + inject labelExpr for large-number axes.
"""

from __future__ import annotations
import copy
import re
from langchain_core.runnables import RunnableConfig

from app.core.logger import logger
from app.services.agents.helpers import _build_data_profile, parse_tag
from app.services.agents.prompts import CHART_LABEL_PROMPT, REASONING_DIRECTIVE_NORMAL
from app.services.agents.state import AnalyticsState

_VALID_CHART_TYPES = {
    "kpi_card", "bar", "bar_horizontal", "line", "area", "multi_line",
    "stacked_area", "pie", "donut", "grouped_bar", "stacked_bar",
    "scatter", "bubble", "heatmap", "waterfall", "dual_axis", "table",
}

# ─── SQL column source extraction (sqlglot) ──────────────────────────────────

def _extract_sql_column_sources(sql: str) -> dict[str, tuple[str, str]]:
    """Parse SQL with sqlglot and map every output alias → (table_fqn, source_column_name).

    Handles the common patterns generated by this pipeline:
      - Qualified references:   lpp.bank_statement_balance.amount AS amount
      - Aggregates:             AVG(amount) AS avg_idle_cash_balance
      - CTE chains:             SELECT * FROM aggregated (expands to CTE columns)
      - Unqualified columns:    searched across FROM / JOIN tables of the CTE scope

    Returns partial results on any failure — no exceptions propagate.
    """
    try:
        import sqlglot
        from sqlglot import exp as sg
    except ImportError:
        return {}

    try:
        stmt = sqlglot.parse_one(sql, read="redshift")
    except Exception:
        return {}

    # table_key (alias or name, lowercased) → full FQN "schema.table"
    tbl_map: dict[str, str] = {}
    for tbl in stmt.find_all(sg.Table):
        if not tbl.name:
            continue
        fqn = f"{tbl.db}.{tbl.name}" if tbl.db else tbl.name
        for key in filter(None, {tbl.name.lower(), (tbl.alias or tbl.name).lower()}):
            tbl_map[key] = fqn

    # CTE name (lower) → Select body
    cte_map: dict[str, sg.Select] = {}
    for cte in stmt.find_all(sg.CTE):
        cte_map[cte.alias.lower()] = cte.this

    _AGG = (sg.Avg, sg.Sum, sg.Count, sg.Min, sg.Max)

    def _resolve(expr, ctx_sel=None, depth: int = 0):
        """Recursively resolve an expression to (table_fqn, col_name) or None."""
        if depth > 8 or expr is None:
            return None
        if isinstance(expr, (sg.Alias, sg.Cast, sg.Paren)):
            return _resolve(expr.this, ctx_sel, depth)
        if isinstance(expr, _AGG):
            return _resolve(expr.this, ctx_sel, depth + 1)
        if isinstance(expr, sg.Column):
            col = expr.name
            tbl = (expr.table or "").lower()
            if tbl:
                if tbl in cte_map:
                    return _find_in_cte(col, cte_map[tbl], depth + 1)
                return (tbl_map.get(tbl, tbl), col)
            if ctx_sel:
                return _find_in_from(col, ctx_sel, depth + 1)
        return None

    def _find_in_cte(col: str, cte_sel, depth: int):
        if depth > 8:
            return None
        for s in cte_sel.selects:
            a = s.alias if isinstance(s, sg.Alias) else (s.name if isinstance(s, sg.Column) else None)
            if a and a.lower() == col.lower():
                inner = s.this if isinstance(s, sg.Alias) else s
                return _resolve(inner, cte_sel, depth + 1)
        return None

    def _find_in_from(col: str, sel, depth: int):
        if depth > 8:
            return None
        from_clause = sel.args.get("from_")
        joins = sel.args.get("joins") or []
        sources = ([from_clause.this] if from_clause else []) + [j.this for j in joins]
        for src in sources:
            if isinstance(src, sg.Table):
                key = (src.alias or src.name or "").lower()
                if key in cte_map:
                    r = _find_in_cte(col, cte_map[key], depth + 1)
                    if r:
                        return r
                elif key in tbl_map:
                    return (tbl_map[key], col)
        return None

    def _expand_select(sel, depth: int = 0) -> dict[str, tuple[str, str]]:
        """Walk a Select node and emit {alias: (table_fqn, col_name)}."""
        if depth > 4:
            return {}
        out: dict[str, tuple[str, str]] = {}
        for s in sel.selects:
            if isinstance(s, sg.Star):
                from_clause = sel.args.get("from_")
                if from_clause:
                    tbl_node = from_clause.find(sg.Table)
                    if tbl_node:
                        key = (tbl_node.alias or tbl_node.name or "").lower()
                        if key in cte_map:
                            out.update(_expand_select(cte_map[key], depth + 1))
                continue
            alias = s.alias if isinstance(s, sg.Alias) else (s.name if isinstance(s, sg.Column) else None)
            if not alias:
                continue
            inner = s.this if isinstance(s, sg.Alias) else s
            src = _resolve(inner, sel)
            if src:
                out[alias] = src
        return out

    try:
        return _expand_select(stmt)
    except Exception:
        return {}


# ─── Column metadata builder ──────────────────────────────────────────────────

def _build_column_metadata(columns: list[str], state: AnalyticsState) -> str:
    """Map result columns → Neo4j catalog descriptions.

    Primary:  sqlglot parses the generated SQL and traces each output alias
              back to its source table.column (works through CTEs, SELECT *,
              aggregates, and complex aliases).
    Fallback: IR measures/dimensions for any column sqlglot could not resolve.
    """
    # sqlglot-based source mapping from the generated SQL
    sql = (state.get("sql_list") or [""])[0]
    col_sources: dict[str, tuple[str, str]] = _extract_sql_column_sources(sql) if sql else {}

    # IR-based fallback for anything sqlglot missed
    ir = (state.get("semantic_ir_list") or [{}])[0]
    for item in list(ir.get("measures") or []) + list(ir.get("dimensions") or []):
        alias = item.get("alias") or item.get("column_name") or ""
        col_name = item.get("column_name") or ""
        table_fqn = item.get("table_fqn") or ""
        if alias and alias not in col_sources and col_name and table_fqn:
            col_sources[alias] = (table_fqn, col_name)

    # (table_fqn, column_name) → Neo4j metadata from schema context
    semantic_ctx = state.get("semantic_context") or {}
    col_meta: dict[tuple[str, str], dict] = {}
    for c in (semantic_ctx.get("columns") or []):
        key = (c.get("table_fqn") or "", c.get("name") or "")
        if key[0] or key[1]:
            col_meta[key] = c

    lines = ["COLUMN METADATA (catalog descriptions — use to pick format, axis labels, color scheme):"]
    for col in columns:
        src = col_sources.get(col)
        meta = col_meta.get(src) if src else None

        desc = (meta.get("description") or "") if meta else ""
        sem_type = (meta.get("semantic_type") or "") if meta else ""
        data_type = (meta.get("data_type") or "") if meta else ""

        parts: list[str] = []
        if data_type:
            parts.append(f"type={data_type}")
        if sem_type:
            parts.append(f"semantic={sem_type}")
        if desc:
            parts.append(f'"{desc}"')

        suffix = "   " + "   ".join(parts) if parts else "   (no catalog entry)"
        lines.append(f"  {col}{suffix}")

    return "\n".join(lines)


# ─── Post-processor — humanize labels + fix large-number axes ─────────────────

def _snake_to_title(s: str) -> str:
    """Convert snake_case / SCREAMING_CASE to Title Case. Leaves already-spaced strings alone."""
    if not s or not isinstance(s, str):
        return s
    if " " in s.strip():
        return s
    words = re.split(r"[_\s]+", s)
    return " ".join(w.capitalize() for w in words if w)


def _humanize_spec_labels(spec: dict) -> dict:
    """Walk Vega-Lite spec and humanize axis/legend titles that are raw identifiers."""
    spec = copy.deepcopy(spec)

    if isinstance(spec.get("title"), str):
        spec["title"] = _snake_to_title(spec["title"])

    encoding = spec.get("encoding")
    if not isinstance(encoding, dict):
        return spec

    for ch in encoding.values():
        if not isinstance(ch, dict):
            continue
        axis = ch.get("axis")
        if isinstance(axis, dict) and isinstance(axis.get("title"), str):
            axis["title"] = _snake_to_title(axis["title"])
        legend = ch.get("legend")
        if isinstance(legend, dict) and isinstance(legend.get("title"), str):
            legend["title"] = _snake_to_title(legend["title"])

    return spec


def _extract_currency_symbol(value_format: str) -> str:
    """Return any currency prefix found in the LLM's value_format string."""
    for sym in ("$", "₹", "€", "£", "¥", "₩", "₦", "₱", "₫", "฿"):
        if sym in (value_format or ""):
            return sym
    return ""


def _col_max_abs(rows: list[list], col_idx: int) -> float | None:
    vals: list[float] = []
    for row in rows:
        v = row[col_idx] if col_idx < len(row) else None
        if v is None:
            continue
        try:
            vals.append(abs(float(v)))
        except (TypeError, ValueError):
            pass
    return max(vals) if vals else None


def _build_label_expr(currency_sym: str = "") -> str:
    """Build a Vega labelExpr for business-friendly K / M / B / T axis labels.

    Replaces d3 format strings like ',.0f' when values are >= 1,000,000.
    Handles positive and negative large values. Currency prefix is optional.
    """
    sym = currency_sym
    q = "'"
    prefix = f"{q}{sym}{q} + " if sym else ""

    def _tier(divisor: str, suffix: str) -> str:
        fmt = f"{q}.2f{q}"
        return f"{prefix}format(datum.value / {divisor}, {fmt}) + {q}{suffix}{q}"

    pos = (
        f"datum.value >= 1e12 ? {_tier('1e12', 'T')} : "
        f"datum.value >= 1e9  ? {_tier('1e9',  'B')} : "
        f"datum.value >= 1e6  ? {_tier('1e6',  'M')} : "
        f"datum.value >= 1e3  ? {_tier('1e3',  'K')} : "
    )
    neg = (
        f"datum.value <= -1e12 ? {_tier('1e12', 'T')} : "
        f"datum.value <= -1e9  ? {_tier('1e9',  'B')} : "
        f"datum.value <= -1e6  ? {_tier('1e6',  'M')} : "
        f"datum.value <= -1e3  ? {_tier('1e3',  'K')} : "
    )
    fallback = f"{prefix}format(datum.value, {q},.0f{q})"
    return pos + neg + fallback


def _fix_large_number_axes(
    spec: dict,
    columns: list[str],
    rows: list[list],
    labels: dict,
) -> dict:
    """Replace axis.format with axis.labelExpr for columns whose values are >= 1,000,000.

    This is what turns '500,000,000,000' into '500B' on the axis.
    Respects currency symbol from LLM's value_format (e.g. '$' → '$500B').
    Only fires when the actual data max confirms it's needed — no guessing.
    """
    encoding = spec.get("encoding")
    if not isinstance(encoding, dict) or not rows:
        return spec

    currency_sym = _extract_currency_symbol(labels.get("value_format") or "")
    spec = copy.deepcopy(spec)
    encoding = spec["encoding"]

    for channel in ("y", "x"):
        ch = encoding.get(channel)
        if not isinstance(ch, dict) or ch.get("type") != "quantitative":
            continue
        field = ch.get("field")
        if not isinstance(field, str) or field not in columns:
            continue
        col_idx = columns.index(field)
        max_val = _col_max_abs(rows, col_idx)
        if max_val is None or max_val < 1_000_000:
            continue

        axis = ch.get("axis")
        if not isinstance(axis, dict):
            axis = {}
            ch["axis"] = axis
        axis.pop("format", None)
        axis["labelExpr"] = _build_label_expr(currency_sym)

    return spec


def _postprocess_spec(
    spec: dict,
    columns: list[str],
    rows: list[list],
    labels: dict,
) -> dict:
    """Apply all post-processing passes to a Vega-Lite spec before sending to frontend."""
    spec = _humanize_spec_labels(spec)
    spec = _fix_large_number_axes(spec, columns, rows, labels)
    return spec


async def chart_agent(state: AnalyticsState, config: RunnableConfig) -> dict:
    query_summary = state.get("query_summary") or {}
    result_list = state.get("result_list") or []
    ir_list = state.get("semantic_ir_list") or []

    all_columns: list[str] = (
        [c["name"] for c in query_summary["columns"]]
        if query_summary.get("columns")
        else []
    )
    all_rows: list[list] = []
    for res in result_list:
        if res.get("rows"):
            if not all_columns and res.get("columns"):
                all_columns = res["columns"]
            all_rows.extend(res["rows"])

    if not all_columns or not all_rows:
        logger.info("chart_agent | no data for chart | thread={}", state["thread_id"])
        return {"chart_spec": None}

    intent = ir_list[0].get("intent", "") if ir_list else ""
    persona = state.get("persona", "executive")

    # Fast path: if guardrails would force the type regardless, skip the LLM call
    forced_type = _apply_guardrails("__probe__", all_columns, all_rows)
    if forced_type == "kpi_card":
        logger.info("chart_agent | fast-path kpi_card (no LLM) | thread={}", state["thread_id"])
        spec = _build_vega_lite_spec("kpi_card", all_columns, all_rows, {})
        return {"chart_spec": spec, "chart_type": "kpi_card", "alternative_chart_specs": []}

    chart_type, labels = await _select_chart_and_labels(
        all_columns, all_rows, query_summary, state, config, intent, persona
    )

    # Safety guardrails that override LLM choice
    chart_type = _apply_guardrails(chart_type, all_columns, all_rows)

    logger.info("chart_agent | selected type={} | thread={} | rows={}", chart_type, state["thread_id"], len(all_rows))

    if chart_type == "table":
        spec = _build_table_spec(all_columns, all_rows)
        return {"chart_spec": spec, "chart_type": chart_type, "alternative_chart_specs": []}

    spec = _postprocess_spec(
        _build_vega_lite_spec(chart_type, all_columns, all_rows, labels),
        all_columns, all_rows, labels,
    )

    # Build alternative specs from LLM-suggested types
    raw_alternatives = labels.get("alternative_types") or []
    alternative_chart_specs = _build_alternative_specs(
        raw_alternatives, chart_type, all_columns, all_rows, labels
    )

    logger.info(
        "chart_agent DONE | thread={} | type={} | alternatives={}",
        state["thread_id"], chart_type, [a["chart_type"] for a in alternative_chart_specs],
    )
    return {"chart_spec": spec, "chart_type": chart_type, "alternative_chart_specs": alternative_chart_specs}


def _build_alternative_specs(
    raw_alternatives: list,
    primary_type: str,
    columns: list[str],
    rows: list[list],
    labels: dict,
) -> list[dict]:
    """Build Vega-Lite specs for each LLM-suggested alternative type.

    Returns a list of {"chart_type": str, "spec": dict} entries.
    Skips any type that duplicates the primary, fails guardrails, or raises during build.
    """
    seen = {primary_type}
    result = []
    for alt_type in raw_alternatives[:3]:
        if not isinstance(alt_type, str):
            continue
        guarded = _apply_guardrails(alt_type, columns, rows)
        if guarded in seen or guarded not in _VALID_CHART_TYPES:
            continue
        seen.add(guarded)
        try:
            if guarded == "table":
                spec = _build_table_spec(columns, rows)
            else:
                spec = _postprocess_spec(
                    _build_vega_lite_spec(guarded, columns, rows, labels),
                    columns, rows, labels,
                )
            result.append({"chart_type": guarded, "spec": spec})
        except Exception as e:
            logger.debug("chart_agent | alt spec failed | type={} | error={}", guarded, e)
    return result


def _apply_guardrails(chart_type: str, columns: list[str], rows: list[list]) -> str:
    """Hard rules that override LLM choice regardless of reasoning."""
    n_rows = len(rows)
    col_types = _classify_column_types(columns, rows)
    n_numeric = col_types.count("numeric")
    n_date = col_types.count("date")

    if n_rows == 1 and n_numeric >= 1:
        return "kpi_card"

    if n_rows <= 5 and n_numeric == len(columns):
        return "kpi_card"

    if chart_type in ("line", "area", "multi_line", "stacked_area") and n_date == 0:
        return "bar"

    if chart_type == "scatter" and (n_numeric < 2 or n_date > 0):
        return "bar"

    if chart_type not in _VALID_CHART_TYPES:
        return "table"

    return chart_type


async def _select_chart_and_labels(
    columns: list[str],
    rows: list[list],
    query_summary: dict,
    state: AnalyticsState,
    config: RunnableConfig,
    intent: str,
    persona: str,
) -> tuple[str, dict]:
    # Build shared data profile (same builder as synthesis)
    data_profile = _build_data_profile(columns, rows, query_summary)

    # Column descriptions from Neo4j catalog — lets LLM pick format semantically
    column_metadata = _build_column_metadata(columns, state)

    fb = state.get("feedback_context") or ""
    feedback_section = (
        f"USER CHART PREFERENCES (apply silently):\n<feedback_context>{fb}</feedback_context>"
        if fb else ""
    )

    prompt = CHART_LABEL_PROMPT.format_messages(
        question=state["question"],
        intent=intent,
        persona=persona,
        data_profile=data_profile,
        column_metadata=column_metadata,
        feedback_section=feedback_section,
        reasoning_directive=REASONING_DIRECTIVE_NORMAL,
    )

    from app.services.agents.bedrock import get_llm
    from app.core.circuit_breaker import llm_breaker

    llm = get_llm("fast")

    @llm_breaker
    async def _call():
        return await llm.ainvoke(prompt, config=config)

    fallback_type = _fallback_chart_type(columns, rows, intent, persona)
    fallback_labels = {
        "chart_type": fallback_type,
        "chart_title": _snake_to_title(state["question"][:60]),
        "x_axis_label": _snake_to_title(columns[0]) if columns else "x",
        "y_axis_label": _snake_to_title(columns[1]) if len(columns) > 1 else "Value",
        "legend_labels": {},
        "value_format": ",.0f",
        "color_scheme": "blues",
    }

    try:
        response = await _call()
        raw = response.content or ""
        output = parse_tag(raw, "chart")
        if output:
            from json_repair import loads as json_loads
            parsed = json_loads(output)
            if isinstance(parsed, dict):
                chart_type = parsed.get("chart_type", fallback_type)
                return chart_type, parsed
    except Exception as e:
        logger.warning("chart_agent | LLM selection failed | error={}", e)

    return fallback_type, fallback_labels


def _fallback_chart_type(columns: list[str], rows: list[list], intent: str, persona: str) -> str:
    """Simple deterministic fallback used only when LLM call fails."""
    if not rows or not columns:
        return "table"
    n_rows = len(rows)
    col_types = _classify_column_types(columns, rows)
    n_numeric = col_types.count("numeric")
    n_date = col_types.count("date")
    n_string = col_types.count("string")

    if n_rows == 1 and n_numeric >= 1:
        return "kpi_card"
    if n_rows <= 5 and n_numeric == len(columns):
        return "kpi_card"
    if n_date >= 1:
        return "area" if persona in ("executive", "director") else "line"
    if n_string == 1 and n_numeric == 1:
        return "bar" if n_rows > 5 else ("donut" if persona in ("executive", "director") else "pie")
    if n_rows > 30:
        return "table"
    return "bar"


def _safe_value_format(fmt: str, rows: list[list], col_idx: int) -> str:
    """Guard against .1% being applied to pre-converted percentage values.
    Vega-Lite .1% multiplies by 100 — correct only for ratios between 0 and 1.
    If values are in range 1–100 (already-converted %) → use ,.1f (e.g. 9.4 shows as "9.4").
    If values are > 100 (dollar amounts, counts) → use ,.0f.
    """
    fmt = fmt.replace("~", "")  # strip d3 trim-zeros flag — not supported in all Vega environments
    if "%" not in fmt:
        return fmt
    try:
        sample = [float(rows[j][col_idx]) for j in range(min(10, len(rows))) if rows[j][col_idx] is not None]
        if sample:
            mx = max(abs(v) for v in sample)
            if mx > 100:
                return ",.0f"
            if mx > 1:
                return ",.1f"
    except (TypeError, ValueError, IndexError):
        pass
    return fmt


def _build_vega_lite_spec(chart_type: str, columns: list[str], rows: list[list], labels: dict) -> dict:
    spec = {
        "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
        "width": "container",
        "height": 350,
        "background": "transparent",
        "title": labels.get("chart_title", ""),
        "data": {"values": [dict(zip(columns, row)) for row in rows[:500]]},
    }

    if chart_type in ("bar", "bar_horizontal"):
        y_col = _find_numeric_col(columns, rows)
        x_col = _find_string_col(columns, rows, exclude=y_col) or (columns[0] if columns else "x")
        spec["mark"] = "bar"
        # bar: category → x (horizontal label), values → y (vertical label)
        # bar_horizontal: category → y (left label), values → x (bottom label)
        # LLM always generates x_axis_label=bottom and y_axis_label=left, so for
        # bar_horizontal the category axis gets y_axis_label and values get x_axis_label.
        if chart_type == "bar":
            cat_label = labels.get("x_axis_label", x_col)
            val_label = labels.get("y_axis_label", y_col)
        else:
            cat_label = labels.get("y_axis_label", x_col)
            val_label = labels.get("x_axis_label", y_col)
        val_format = _safe_value_format(labels.get("value_format", ",.0f"), rows, columns.index(y_col) if y_col in columns else -1)
        spec["encoding"] = {
            "x" if chart_type == "bar" else "y": {
                "field": x_col, "type": "nominal",
                "axis": {"title": cat_label},
                "sort": "-y" if chart_type == "bar" else "-x",
            },
            "y" if chart_type == "bar" else "x": {
                "field": y_col, "type": "quantitative",
                "axis": {"title": val_label, "format": val_format},
            },
        }

    elif chart_type in ("line", "area"):
        x_col = _find_date_col(columns, rows)
        y_col = _find_numeric_col(columns, rows, exclude=x_col)
        spec["mark"] = chart_type
        spec["encoding"] = {
            "x": {"field": x_col, "type": "temporal", "timeUnit": "yearmonthdate", "axis": {"title": labels.get("x_axis_label", x_col), "format": "%b %d, %Y"}},
            "y": {"field": y_col, "type": "quantitative", "axis": {"title": labels.get("y_axis_label", y_col), "format": labels.get("value_format", ",.0f")}},
        }

    elif chart_type in ("multi_line", "stacked_area"):
        x_col = _find_date_col(columns, rows)
        cat_col = _find_string_col(columns, rows, exclude=x_col)
        y_col = _find_numeric_col(columns, rows, exclude=x_col)
        mark = "line" if chart_type == "multi_line" else "area"
        spec["mark"] = mark
        encoding: dict = {
            "x": {"field": x_col, "type": "temporal", "timeUnit": "yearmonthdate", "axis": {"title": labels.get("x_axis_label", x_col), "format": "%b %d, %Y"}},
            "y": {"field": y_col, "type": "quantitative", "axis": {"title": labels.get("y_axis_label", y_col)}},
            "color": {"field": cat_col, "type": "nominal"},
        }
        if chart_type == "stacked_area":
            encoding["y"]["stack"] = "zero"
        spec["encoding"] = encoding

    elif chart_type in ("pie", "donut"):
        name_col = _find_string_col(columns, rows)
        value_col = _find_numeric_col(columns, rows)
        spec["mark"] = {"type": "arc", "innerRadius": 50 if chart_type == "donut" else 0}
        spec["encoding"] = {
            "theta": {"field": value_col, "type": "quantitative"},
            "color": {"field": name_col, "type": "nominal"},
        }

    elif chart_type == "kpi_card":
        spec["type"] = "kpi_card"
        spec["values"] = [dict(zip(columns, row)) for row in rows[:3]]
        return spec

    elif chart_type in ("grouped_bar", "stacked_bar"):
        string_cols = [c for i, c in enumerate(columns) if _classify_column_types(columns, rows)[i] == "string"]
        x_col = string_cols[0] if string_cols else columns[0]
        cat_col = string_cols[1] if len(string_cols) > 1 else (string_cols[0] if string_cols else columns[0])
        y_col = _find_numeric_col(columns, rows)
        spec["mark"] = "bar"
        encoding = {
            "x": {"field": x_col, "type": "nominal", "axis": {"title": labels.get("x_axis_label", x_col)}},
            "y": {"field": y_col, "type": "quantitative", "axis": {"title": labels.get("y_axis_label", y_col), "format": labels.get("value_format", ",.0f")}},
            "color": {"field": cat_col, "type": "nominal"},
        }
        if chart_type == "stacked_bar":
            encoding["y"]["stack"] = "zero"
        else:
            encoding["xOffset"] = {"field": cat_col}
        spec["encoding"] = encoding

    elif chart_type == "scatter":
        x_col = _find_numeric_col(columns, rows)
        y_col = _find_numeric_col(columns, rows, exclude=x_col)
        spec["mark"] = "point"
        spec["encoding"] = {
            "x": {"field": x_col, "type": "quantitative", "axis": {"title": labels.get("x_axis_label", x_col)}},
            "y": {"field": y_col, "type": "quantitative", "axis": {"title": labels.get("y_axis_label", y_col)}},
        }

    else:
        spec["mark"] = "bar"
        if columns:
            spec["encoding"] = {
                "x": {"field": columns[0], "type": "nominal"},
                "y": {"field": columns[1] if len(columns) > 1 else columns[0], "type": "quantitative"},
            }

    spec["config"] = {
        "axis": {"labelFont": "Inter, sans-serif", "titleFont": "Inter, sans-serif"},
        "legend": {"labelFont": "Inter, sans-serif"},
    }
    return spec


def _build_table_spec(columns: list[str], rows: list[list]) -> dict:
    return {
        "type": "table",
        "columns": columns,
        "rows": [list(r) for r in rows[:200]],
    }


def _classify_column_types(columns: list[str], rows: list[list]) -> list[str]:
    import re
    result = []
    for i in range(len(columns)):
        sample = [rows[j][i] for j in range(min(20, len(rows))) if rows[j][i] is not None]
        if not sample:
            result.append("unknown")
            continue
        try:
            [float(v) for v in sample]
            result.append("numeric")
            continue
        except (TypeError, ValueError):
            pass
        if re.match(r"\d{4}-\d{2}-\d{2}", str(sample[0])):
            result.append("date")
            continue
        result.append("string")
    return result


def _find_date_col(columns: list[str], rows: list[list]) -> str:
    import re
    for i, col in enumerate(columns):
        sample = [str(rows[j][i]) for j in range(min(5, len(rows))) if rows[j][i] is not None]
        if sample and re.match(r"\d{4}-\d{2}-\d{2}", sample[0]):
            return col
    return columns[0] if columns else "date"


def _find_numeric_col(columns: list[str], rows: list[list], exclude: str | None = None) -> str:
    for i, col in enumerate(columns):
        if col == exclude:
            continue
        sample = [rows[j][i] for j in range(min(5, len(rows))) if rows[j][i] is not None]
        try:
            [float(v) for v in sample]
            return col
        except (TypeError, ValueError):
            pass
    return columns[-1] if columns else "value"


def _find_string_col(columns: list[str], rows: list[list], exclude: str | None = None) -> str:
    for i, col in enumerate(columns):
        if col == exclude:
            continue
        sample = [rows[j][i] for j in range(min(5, len(rows))) if rows[j][i] is not None]
        try:
            [float(v) for v in sample]
        except (TypeError, ValueError):
            return col
    return columns[0] if columns else "category"
