"""Node 5: chart_agent — selects chart type and generates Vega-Lite labels.

Step 1: LLM selects chart type AND generates labels in one call (semantic, persona-aware).
        LLM receives column descriptions from Neo4j — knows if a column is USD, count, ratio, etc.
Step 2: Hard safety guardrails applied after LLM choice (single row → kpi_card, etc.).
Step 3: Programmatic Vega-Lite spec builder injects fixed fields and data rows.
Step 4: Post-processor — humanize labels + inject labelExpr for large-number axes.
"""

from __future__ import annotations
import copy
import re
from langchain_core.runnables import RunnableConfig

from app.core.logger import logger
from app.services.agents.helpers import _build_data_profile, parse_tag
from app.services.agents.prompts import CHART_LABEL_PROMPT, CHART_PLAN_PROMPT, REASONING_DIRECTIVE_NORMAL
from app.services.agents.state import AnalyticsState

_VALID_CHART_TYPES = {
    "kpi_card", "bar", "bar_horizontal", "line", "area", "multi_line",
    "stacked_area", "pie", "donut", "grouped_bar", "stacked_bar",
    "scatter", "bubble", "heatmap", "waterfall", "dual_axis",
}


def _drop_blank_columns(columns: list[str], rows: list[list]) -> tuple[list[str], list[list]]:
    """Drop columns where every value is None, NaN, 0, '0', or '' — they produce blank charts."""
    import math
    if not rows or not columns:
        return columns, rows

    def _is_blank(v) -> bool:
        if v is None:
            return True
        if isinstance(v, float) and math.isnan(v):
            return True
        return v in (0, 0.0, "", "0")

    keep = [
        i for i, _ in enumerate(columns)
        if any(
            not _is_blank(row[i])
            for row in rows
            if i < len(row)
        )
    ]
    if len(keep) == len(columns):
        return columns, rows
    new_cols = [columns[i] for i in keep]
    new_rows = [[row[i] for i in keep if i < len(row)] for row in rows]
    return new_cols, new_rows


def _build_col_type_map(columns: list[str], rows: list[list]) -> dict[str, str]:
    """Build a normalized col_type_map using pandas on the actual data.

    Redshift returns raw dtype strings like 'timestamp without time zone',
    'double precision', 'character varying' — these cannot be directly compared
    against 'date'/'numeric'/'string'. Pandas infers types from actual values,
    which is authoritative and handles all Redshift type variants.

    Returns: {col_name: 'numeric' | 'date' | 'string'}
    """
    import pandas as pd
    if not rows or not columns:
        return {}
    sample = rows[:200]
    try:
        df = pd.DataFrame(sample, columns=columns)
    except Exception:
        return {c: "string" for c in columns}

    result: dict[str, str] = {}
    for i, col in enumerate(columns):
        series = df[col].dropna()
        if series.empty:
            result[col] = "string"
            continue
        # Boolean columns (True/False) must be "string" — they are categorical flags,
        # not measures. Without this, is_closed/has_recent_activity (False=0) get
        # picked as the first numeric column by _num() and render as a flat "0" bar.
        if pd.api.types.is_bool_dtype(series):
            result[col] = "string"
            continue
        if pd.api.types.is_numeric_dtype(series):
            result[col] = "numeric"
            continue
        str_series = series.astype(str)
        if str_series.str.match(r"^\d{4}-\d{2}-\d{2}").any():
            result[col] = "date"
            continue
        result[col] = "string"
    return result

# ─── SQL column source extraction (sqlglot) ──────────────────────────────────

def _extract_sql_column_sources(sql: str) -> dict[str, tuple[str, str]]:
    """Parse SQL with sqlglot and map every output alias → (table_fqn, source_column_name).

    Handles the common patterns generated by this pipeline:
      - Qualified references:   lpp.bank_statement_balance.amount AS amount
      - Aggregates:             AVG(amount) AS avg_idle_cash_balance
      - CTE chains:             SELECT * FROM aggregated (expands to CTE columns)
      - Unqualified columns:    searched across FROM / JOIN tables of the CTE scope

    Returns partial results on any failure — no exceptions propagate.
    """
    try:
        import sqlglot
        from sqlglot import exp as sg
    except ImportError:
        return {}

    try:
        stmt = sqlglot.parse_one(sql, read="redshift")
    except Exception:
        return {}

    # table_key (alias or name, lowercased) → full FQN "schema.table"
    tbl_map: dict[str, str] = {}
    for tbl in stmt.find_all(sg.Table):
        if not tbl.name:
            continue
        fqn = f"{tbl.db}.{tbl.name}" if tbl.db else tbl.name
        for key in filter(None, {tbl.name.lower(), (tbl.alias or tbl.name).lower()}):
            tbl_map[key] = fqn

    # CTE name (lower) → Select body
    cte_map: dict[str, sg.Select] = {}
    for cte in stmt.find_all(sg.CTE):
        cte_map[cte.alias.lower()] = cte.this

    _AGG = (sg.Avg, sg.Sum, sg.Count, sg.Min, sg.Max)

    def _resolve(expr, ctx_sel=None, depth: int = 0):
        """Recursively resolve an expression to (table_fqn, col_name) or None."""
        if depth > 8 or expr is None:
            return None
        if isinstance(expr, (sg.Alias, sg.Cast, sg.Paren)):
            return _resolve(expr.this, ctx_sel, depth)
        if isinstance(expr, _AGG):
            return _resolve(expr.this, ctx_sel, depth + 1)
        if isinstance(expr, sg.Column):
            col = expr.name
            tbl = (expr.table or "").lower()
            if tbl:
                if tbl in cte_map:
                    return _find_in_cte(col, cte_map[tbl], depth + 1)
                return (tbl_map.get(tbl, tbl), col)
            if ctx_sel:
                return _find_in_from(col, ctx_sel, depth + 1)
        return None

    def _find_in_cte(col: str, cte_sel, depth: int):
        if depth > 8:
            return None
        for s in cte_sel.selects:
            a = s.alias if isinstance(s, sg.Alias) else (s.name if isinstance(s, sg.Column) else None)
            if a and a.lower() == col.lower():
                inner = s.this if isinstance(s, sg.Alias) else s
                return _resolve(inner, cte_sel, depth + 1)
        return None

    def _find_in_from(col: str, sel, depth: int):
        if depth > 8:
            return None
        from_clause = sel.args.get("from_")
        joins = sel.args.get("joins") or []
        sources = ([from_clause.this] if from_clause else []) + [j.this for j in joins]
        for src in sources:
            if isinstance(src, sg.Table):
                key = (src.alias or src.name or "").lower()
                if key in cte_map:
                    r = _find_in_cte(col, cte_map[key], depth + 1)
                    if r:
                        return r
                elif key in tbl_map:
                    return (tbl_map[key], col)
        return None

    def _expand_select(sel, depth: int = 0) -> dict[str, tuple[str, str]]:
        """Walk a Select node and emit {alias: (table_fqn, col_name)}."""
        if depth > 4:
            return {}
        out: dict[str, tuple[str, str]] = {}
        for s in sel.selects:
            if isinstance(s, sg.Star):
                from_clause = sel.args.get("from_")
                if from_clause:
                    tbl_node = from_clause.find(sg.Table)
                    if tbl_node:
                        key = (tbl_node.alias or tbl_node.name or "").lower()
                        if key in cte_map:
                            out.update(_expand_select(cte_map[key], depth + 1))
                continue
            alias = s.alias if isinstance(s, sg.Alias) else (s.name if isinstance(s, sg.Column) else None)
            if not alias:
                continue
            inner = s.this if isinstance(s, sg.Alias) else s
            src = _resolve(inner, sel)
            if src:
                out[alias] = src
        return out

    try:
        return _expand_select(stmt)
    except Exception:
        return {}


# ─── Column metadata builder ──────────────────────────────────────────────────

def _build_column_metadata(columns: list[str], state: AnalyticsState) -> str:
    """Map result columns → Neo4j catalog descriptions.

    Primary:  sqlglot parses the generated SQL and traces each output alias
              back to its source table.column (works through CTEs, SELECT *,
              aggregates, and complex aliases).
    Fallback: IR measures/dimensions for any column sqlglot could not resolve.
    """
    # sqlglot-based source mapping from the generated SQL
    sql = (state.get("sql_list") or [""])[0]
    col_sources: dict[str, tuple[str, str]] = _extract_sql_column_sources(sql) if sql else {}

    # IR-based fallback for anything sqlglot missed
    ir = (state.get("semantic_ir_list") or [{}])[0]
    for item in list(ir.get("measures") or []) + list(ir.get("dimensions") or []):
        alias = item.get("alias") or item.get("column_name") or ""
        col_name = item.get("column_name") or ""
        table_fqn = item.get("table_fqn") or ""
        if alias and alias not in col_sources and col_name and table_fqn:
            col_sources[alias] = (table_fqn, col_name)

    # (table_fqn, column_name) → Neo4j metadata from schema context
    semantic_ctx = state.get("semantic_context") or {}
    col_meta: dict[tuple[str, str], dict] = {}
    for c in (semantic_ctx.get("columns") or []):
        key = (c.get("table_fqn") or "", c.get("name") or "")
        if key[0] or key[1]:
            col_meta[key] = c

    lines = ["COLUMN METADATA (semantic type, data type, and description — use to pick format, axis labels, value scale, and chart type):"]
    for col in columns:
        src = col_sources.get(col)
        meta = col_meta.get(src) if src else None

        sem_type   = (meta.get("semantic_type") or "") if meta else ""
        data_type  = (meta.get("data_type") or "") if meta else ""
        description = (meta.get("description") or "") if meta else ""

        parts: list[str] = []
        if data_type:
            parts.append(f"type={data_type}")
        if sem_type:
            parts.append(f"semantic={sem_type}")
        if description:
            parts.append(f"desc={description[:80]}")

        suffix = "   " + "   ".join(parts) if parts else "   (no catalog entry)"
        lines.append(f"  {col}{suffix}")

    return "\n".join(lines)


# ─── Post-processor — humanize labels + fix large-number axes ─────────────────

def _snake_to_title(s: str) -> str:
    """Convert snake_case / SCREAMING_CASE to Title Case. Leaves already-spaced strings alone."""
    if not s or not isinstance(s, str):
        return s
    if " " in s.strip():
        return s
    words = re.split(r"[_\s]+", s)
    return " ".join(w.capitalize() for w in words if w)


def _humanize_spec_labels(spec: dict) -> dict:
    """Walk Vega-Lite spec and humanize axis/legend/tooltip titles that are raw identifiers."""
    spec = copy.deepcopy(spec)

    if isinstance(spec.get("title"), str):
        spec["title"] = _snake_to_title(spec["title"])

    def _humanize_tooltip_list(tooltip_list: list) -> None:
        for item in tooltip_list:
            if not isinstance(item, dict):
                continue
            existing = item.get("title")
            if existing is None:
                field = item.get("field", "")
                if field:
                    item["title"] = _snake_to_title(field)
            elif isinstance(existing, str) and ("_" in existing or existing.isupper()):
                item["title"] = _snake_to_title(existing)

    def _humanize_encoding(encoding: dict) -> None:
        # Top-level tooltip array (most chart types put tooltip directly in encoding,
        # not nested inside a channel object)
        top_tt = encoding.get("tooltip")
        if isinstance(top_tt, list):
            _humanize_tooltip_list(top_tt)

        for ch in encoding.values():
            if not isinstance(ch, dict):
                continue
            axis = ch.get("axis")
            if isinstance(axis, dict) and isinstance(axis.get("title"), str):
                axis["title"] = _snake_to_title(axis["title"])
            legend = ch.get("legend")
            if isinstance(legend, dict) and isinstance(legend.get("title"), str):
                legend["title"] = _snake_to_title(legend["title"])
            tooltip = ch.get("tooltip")
            if isinstance(tooltip, list):
                _humanize_tooltip_list(tooltip)

    encoding = spec.get("encoding")
    if isinstance(encoding, dict):
        _humanize_encoding(encoding)

    for layer in spec.get("layer", []):
        if isinstance(layer, dict):
            layer_enc = layer.get("encoding")
            if isinstance(layer_enc, dict):
                _humanize_encoding(layer_enc)

    return spec


def _extract_currency_symbol(value_format: str) -> str:
    """Return any currency prefix found in the LLM's value_format string."""
    for sym in ("$", "₹", "€", "£", "¥", "₩", "₦", "₱", "₫", "฿"):
        if sym in (value_format or ""):
            return sym
    return ""


def _col_max_abs(rows: list[list], col_idx: int) -> float | None:
    vals: list[float] = []
    for row in rows:
        v = row[col_idx] if col_idx < len(row) else None
        if v is None:
            continue
        try:
            vals.append(abs(float(v)))
        except (TypeError, ValueError):
            pass
    return max(vals) if vals else None


def _col_p99(rows: list[list], col_idx: int) -> float | None:
    """99th percentile of absolute values in a column."""
    vals: list[float] = []
    for row in rows:
        v = row[col_idx] if col_idx < len(row) else None
        if v is None:
            continue
        try:
            vals.append(abs(float(v)))
        except (TypeError, ValueError):
            pass
    if not vals:
        return None
    vals.sort()
    idx = max(0, int(len(vals) * 0.99) - 1)
    return vals[idx]


def _build_label_expr(currency_sym: str = "") -> str:
    """Build a Vega labelExpr for business-friendly K / M / B / T axis labels.

    Replaces d3 format strings like ',.0f' when values are >= 1,000,000.
    Handles positive and negative large values. Currency prefix is optional.
    """
    sym = currency_sym
    q = "'"
    prefix = f"{q}{sym}{q} + " if sym else ""

    def _tier(divisor: str, suffix: str) -> str:
        fmt = f"{q}.2f{q}"
        return f"{prefix}format(datum.value / {divisor}, {fmt}) + {q}{suffix}{q}"

    pos = (
        f"datum.value >= 1e12 ? {_tier('1e12', 'T')} : "
        f"datum.value >= 1e9  ? {_tier('1e9',  'B')} : "
        f"datum.value >= 1e6  ? {_tier('1e6',  'M')} : "
        f"datum.value >= 1e3  ? {_tier('1e3',  'K')} : "
    )
    neg = (
        f"datum.value <= -1e12 ? {_tier('1e12', 'T')} : "
        f"datum.value <= -1e9  ? {_tier('1e9',  'B')} : "
        f"datum.value <= -1e6  ? {_tier('1e6',  'M')} : "
        f"datum.value <= -1e3  ? {_tier('1e3',  'K')} : "
    )
    fallback = f"{prefix}format(datum.value, {q},.0f{q})"
    return pos + neg + fallback


def _fix_large_number_axes(
    spec: dict,
    columns: list[str],
    rows: list[list],
    labels: dict,
) -> dict:
    """Replace axis.format with axis.labelExpr for columns whose values are >= 1,000,000.

    This is what turns '500,000,000,000' into '500B' on the axis.
    Respects currency symbol from LLM's value_format (e.g. '$' → '$500B').
    Only fires when the actual data max confirms it's needed — no guessing.
    """
    encoding = spec.get("encoding")
    if not isinstance(encoding, dict) or not rows:
        return spec

    spec = copy.deepcopy(spec)
    encoding = spec["encoding"]

    # Compute the global max across all known columns once.
    # Used as a fallback when a quantitative axis field is derived (_wf_sum, _value,
    # _series etc.) and therefore not in the `columns` list.
    # If any source column's values are ≥ 1M, all quantitative axes should use K/M/B/T.
    global_numeric_max: float = 0.0
    for i in range(len(columns)):
        v = _col_max_abs(rows, i)
        if v is not None and v > global_numeric_max:
            global_numeric_max = v

    for channel in ("y", "x"):
        ch = encoding.get(channel)
        if not isinstance(ch, dict) or ch.get("type") != "quantitative":
            continue

        # Per-channel format: y_value_format for y-axis, x_value_format for x-axis.
        # Falls back to global value_format for backward compat (no per-axis keys set).
        fmt = (labels.get(f"{channel}_value_format") or labels.get("value_format") or "")
        currency_sym = _extract_currency_symbol(fmt)
        non_dollar = bool(currency_sym and currency_sym != "$")

        field = ch.get("field")
        if isinstance(field, str) and field in columns:
            col_idx = columns.index(field)
            max_val = _col_max_abs(rows, col_idx)
        else:
            # Derived field (e.g. _wf_sum from waterfall, _value from fold).
            # Use the global max of source columns as proxy.
            max_val = global_numeric_max or None

        # Non-$ currency symbols (€ £ ¥ etc.) are not valid D3 format tokens.
        # Always replace axis.format with labelExpr for those, regardless of magnitude.
        # For plain $ or no currency, replace only when values are large (≥ 1 M).
        if non_dollar:
            pass  # always apply
        else:
            if max_val is None or max_val < 1_000_000:
                continue

        axis = ch.get("axis")
        if not isinstance(axis, dict):
            axis = {}
            ch["axis"] = axis
        axis.pop("format", None)
        axis["labelExpr"] = _build_label_expr(currency_sym)
        # K/M/B scale and a "(%) " unit marker are contradictory — strip the % unit
        # so the title reflects what the ticks actually show (e.g. "9.00B", not "9.00B %")
        _title = axis.get("title")
        if isinstance(_title, str) and "%" in _title:
            _cleaned = re.sub(r"\s*\(\s*%\s*\)", "", _title).strip()
            _cleaned = re.sub(r"\s+%$", "", _cleaned).strip()
            if _cleaned != _title:
                axis["title"] = _cleaned

        # Outlier clamping: when one entity's value is 100× the 99th-percentile
        # (e.g. GR_TREASURY at 50T vs other entities at 50B), the auto-scale
        # compresses all other series into invisible slivers. Clamp domainMax to
        # p99 × 1.1 so the chart remains readable; clamp=True prevents marks from
        # being hidden (they render at the edge instead).
        if isinstance(field, str) and field in columns:
            p99 = _col_p99(rows, columns.index(field))
            if p99 and max_val and max_val > 100 * p99:
                ch.setdefault("scale", {})["domainMax"] = p99 * 1.1
                ch["scale"]["clamp"] = True

    return spec


def _fix_large_number_tooltips(
    spec: dict,
    columns: list[str],
    rows: list[list],
    labels: dict,
) -> dict:
    """Patch tooltip format for large-number / non-ASCII-currency fields.

    D3 format strings only support '$' as a currency symbol — '€', '£', '¥'
    etc. are not valid D3 format tokens and would either error or be ignored.
    axis.labelExpr (Vega expression) sidesteps this, but that mechanism is
    not available for tooltips.

    Solution: use a custom Vega formatType "smartNum" registered in the
    frontend (message-visualization.tsx).  The function signature is
    smartNum(value, currencyPrefix) and returns strings like "€50.7T",
    "£5B", "$1.2M", "50.7T".

    We set:
      "formatType": "smartNum"
      "format": currency_sym   (e.g. "€", "£", "$", "")

    Triggered when: values ≥ 1M OR a non-$ currency is present (same
    threshold as _fix_large_number_axes so axis and tooltip stay in sync).
    """
    spec = copy.deepcopy(spec)

    global_numeric_max: float = 0.0
    for i in range(len(columns)):
        v = _col_max_abs(rows, i)
        if v is not None and v > global_numeric_max:
            global_numeric_max = v

    encoding = spec.get("encoding") or {}
    field_to_channel: dict[str, str] = {}
    for ch_name in ("x", "y", "size"):
        ch = encoding.get(ch_name)
        if isinstance(ch, dict):
            f = ch.get("field")
            if f:
                field_to_channel[f] = ch_name

    def _patch_tooltip_list(tooltip_list: list) -> None:
        for item in tooltip_list:
            if not isinstance(item, dict) or item.get("type") != "quantitative":
                continue
            field = item.get("field")
            if isinstance(field, str) and field in columns:
                max_val = _col_max_abs(rows, columns.index(field))
            else:
                max_val = global_numeric_max or None

            channel = field_to_channel.get(field or "", "y")
            fmt_str = labels.get(f"{channel}_value_format") or labels.get("value_format") or ""
            currency_sym = _extract_currency_symbol(fmt_str)
            non_dollar = bool(currency_sym and currency_sym != "$")

            if not non_dollar and (max_val is None or max_val < 1_000_000):
                continue

            item.pop("format", None)
            item["formatType"] = "smartNum"
            item["format"] = currency_sym or ""

    tt = encoding.get("tooltip")
    if isinstance(tt, list):
        _patch_tooltip_list(tt)

    for layer in spec.get("layer", []):
        if not isinstance(layer, dict):
            continue
        layer_tt = (layer.get("encoding") or {}).get("tooltip")
        if isinstance(layer_tt, list):
            _patch_tooltip_list(layer_tt)

    return spec


def _fix_truncated_time_axis(spec: dict, query_summary: dict | None) -> dict:
    """Set X-axis domain to true date range from ColumnStat when result was truncated.

    When was_truncated=True, the Vega spec has rows only from the capped window
    (e.g. first 100 rows = 3-4 days of a 90-day query). The X-axis auto-scales
    to that narrow window and makes the chart look like 3-4 days of data.
    Setting domain to [true_min, true_max] (from the stats query) makes the axis
    span the full time range, showing where the data actually falls.
    """
    if not query_summary or not query_summary.get("was_truncated"):
        return spec

    date_col_stat = next(
        (c for c in (query_summary.get("columns") or [])
         if c.get("dtype") == "date" and c.get("min") and c.get("max")),
        None,
    )
    if not date_col_stat:
        return spec

    domain = [str(date_col_stat["min"]), str(date_col_stat["max"])]
    logger.debug(
        "chart_agent | _fix_truncated_time_axis | domain=[{}, {}]",
        domain[0], domain[1],
    )
    spec = copy.deepcopy(spec)

    def _apply_domain(encoding: dict) -> None:
        for ch in encoding.values():
            if not isinstance(ch, dict):
                continue
            field_type = ch.get("type", "")
            if field_type == "temporal" and ch.get("field"):
                ch.setdefault("scale", {})["domain"] = domain

    if isinstance(spec.get("encoding"), dict):
        _apply_domain(spec["encoding"])
    for layer in spec.get("layer", []):
        if isinstance(layer, dict) and isinstance(layer.get("encoding"), dict):
            _apply_domain(layer["encoding"])

    return spec


def _postprocess_spec(
    spec: dict,
    columns: list[str],
    rows: list[list],
    labels: dict,
    query_summary: dict | None = None,
) -> dict:
    """Apply all post-processing passes to a Vega-Lite spec before sending to frontend."""
    spec = _humanize_spec_labels(spec)
    spec = _fix_large_number_axes(spec, columns, rows, labels)
    spec = _fix_large_number_tooltips(spec, columns, rows, labels)
    spec = _fix_truncated_time_axis(spec, query_summary)
    return spec


async def chart_agent(state: AnalyticsState, config: RunnableConfig) -> dict:
    query_summary = state.get("query_summary") or {}
    result_list = state.get("result_list") or []
    ir_list = state.get("semantic_ir_list") or []

    all_columns: list[str] = (
        [c["name"] for c in query_summary["columns"]]
        if query_summary.get("columns")
        else []
    )
    all_rows: list[list] = []
    for res in result_list:
        if res.get("rows"):
            if not all_columns and res.get("columns"):
                all_columns = res["columns"]
            all_rows.extend(res["rows"])

    if not all_columns or not all_rows:
        logger.warning(
            "chart_agent | no data | thread={} | query_summary_cols={} | result_list_lens={}",
            state["thread_id"],
            len(query_summary.get("columns", [])),
            [len(r.get("rows", [])) for r in result_list],
        )
        return {"chart_spec": None}

    # Strip columns where every value is 0/null — they cause blank charts when picked as metrics
    all_columns, all_rows = _drop_blank_columns(all_columns, all_rows)
    if not all_columns:
        logger.info("chart_agent | all columns blank after filtering | thread={}", state["thread_id"])
        return {"chart_spec": None}

    intent = ir_list[0].get("intent", "") if ir_list else ""
    persona = state.get("persona", "executive")

    # Build col_type_map from actual data using pandas — raw Redshift dtype strings
    # like "timestamp without time zone" / "double precision" are not reliable for
    # direct string comparison. Pandas infers from values, which is always correct.
    col_type_map = _build_col_type_map(all_columns, all_rows)

    n_rows = len(all_rows)

    chart_type, labels = await _select_chart_and_labels(
        all_columns, all_rows, query_summary, state, config, intent, persona
    )

    # Safety guardrails: structural impossibilities (no date col for time series, unknown type)
    chart_type = _apply_guardrails(chart_type, all_columns, col_type_map, n_rows)
    # Data-aware sanitizer: requires inspecting actual values (negative pie theta, etc.)
    chart_type = _sanitize_chart_type(chart_type, all_columns, all_rows, col_type_map)

    logger.info("chart_agent | selected type={} | thread={} | rows={}", chart_type, state["thread_id"], len(all_rows))

    if chart_type == "table":
        logger.info("chart_agent | chart_type=table → no chart spec (frontend table handles this) | thread={}", state["thread_id"])
        return {"chart_spec": None, "chart_type": "table", "alternative_chart_specs": []}

    spec = _postprocess_spec(
        _build_vega_lite_spec(chart_type, all_columns, all_rows, labels, col_type_map),
        all_columns, all_rows, labels,
        query_summary=query_summary,
    )

    if not _validate_spec(spec, chart_type):
        logger.info(
            "chart_agent | spec validation failed — returning null | type={} | thread={}",
            chart_type, state["thread_id"],
        )
        return {"chart_spec": None, "chart_type": None, "alternative_chart_specs": []}

    raw_alternatives = labels.get("alternative_types") or []
    alternative_specs = _build_alternative_specs(raw_alternatives, chart_type, all_columns, all_rows, labels, col_type_map, query_summary=query_summary)

    logger.info(
        "chart_agent DONE | thread={} | type={} | alternatives={}",
        state["thread_id"], chart_type, [a["chart_type"] for a in alternative_specs],
    )
    return {"chart_spec": spec, "chart_type": chart_type, "alternative_chart_specs": alternative_specs}


def _build_alternative_specs(
    raw_alternatives: list,
    primary_type: str,
    columns: list[str],
    rows: list[list],
    labels: dict,
    col_type_map: dict | None = None,
    query_summary: dict | None = None,
) -> list[dict]:
    """Build Vega-Lite specs for each LLM-suggested alternative type.

    Each alternative uses its own chart_title / x_axis_label / y_axis_label from
    labels["alternative_labels"][alt_type] when the LLM provided them, so axes
    always reflect what THAT chart type puts on each axis rather than copying the
    primary chart's labels (e.g. "Forecast Period (Week Ending)" is wrong as an
    x-axis label for a bar chart whose x is a category column).

    Returns a list of {"chart_type": str, "spec": dict} entries.
    Skips any type that duplicates the primary, fails guardrails, or raises during build.
    """
    # Pairs that are visually equivalent — never show both.
    _REDUNDANT_PAIRS: set[frozenset] = {frozenset({"bar", "bar_horizontal"})}

    # Per-alternative label overrides supplied by the LLM
    alt_label_map: dict = labels.get("alternative_labels") or {}

    _ALT_CONFIDENCE_THRESHOLD = 60

    seen = {primary_type, "table"}
    result = []
    for alt_item in raw_alternatives[:3]:
        # Support both plain strings (legacy) and objects {"type": "...", "x_column": ...}
        if isinstance(alt_item, dict):
            alt_type = alt_item.get("type", "")
            alt_col_hints = {
                k: alt_item.get(k)
                for k in ("x_column", "y_column", "color_column", "size_column")
            }
            alt_confidence = int(alt_item.get("confidence", 100))
        elif isinstance(alt_item, str):
            alt_type = alt_item
            alt_col_hints = {}
            alt_confidence = 100
        else:
            continue
        if not alt_type:
            continue
        if alt_confidence < _ALT_CONFIDENCE_THRESHOLD:
            continue
        guarded = _apply_guardrails(alt_type, columns, col_type_map or {}, len(rows))
        if guarded in seen or guarded not in _VALID_CHART_TYPES:
            continue
        if any(frozenset({primary_type, guarded}) == pair for pair in _REDUNDANT_PAIRS):
            continue
        seen.add(guarded)
        try:
            # Merge: primary labels ← per-alt column hints ← per-alt label overrides.
            # Column hints from plan come before label overrides so labels win on text fields.
            alt_override = alt_label_map.get(guarded) or alt_label_map.get(alt_type) or {}
            alt_labels = {**labels, **alt_col_hints, **alt_override}
            spec = _postprocess_spec(
                _build_vega_lite_spec(guarded, columns, rows, alt_labels, col_type_map),
                columns, rows, alt_labels,
                query_summary=query_summary,
            )
            result.append({"chart_type": guarded, "spec": spec})
        except Exception as e:
            logger.debug("chart_agent | alt spec failed | type={} | error={}", guarded, e)
    return result


def _sanitize_chart_type(
    chart_type: str,
    columns: list[str],
    rows: list[list],
    col_type_map: dict,
) -> str:
    """Data-aware corrections that require inspecting actual row values.

    Called AFTER _apply_guardrails. Catches cases the structural guardrail can't
    detect without looking at the data (e.g. negative values in pie/donut).
    """
    if chart_type in ("pie", "donut"):
        for i, c in enumerate(columns):
            if col_type_map.get(c) == "numeric":
                try:
                    if any(i < len(r) and r[i] is not None and float(r[i]) < 0 for r in rows[:50]):
                        return "bar"
                except (TypeError, ValueError):
                    pass

    # Return "table" only when EVERY meaningful metric column is flat (all values identical).
    # Skip this check for kpi_card — a single summary value is trivially "all identical"
    # (there's only 1 row) but is absolutely correct to display as a KPI card.
    if chart_type == "kpi_card":
        return chart_type

    # Skip boolean-like columns (only values 0 and 1) — those are flags, not measures.
    # A chart is still worth showing if any real metric has variation.
    #
    # Example: account_balance=all $0, is_closed=0/1 mix → is_closed is a flag, skip it.
    # account_balance is the real metric and it's flat → return "table".
    numeric_cols_present = [c for c in columns if col_type_map.get(c) == "numeric" and c in columns]
    if numeric_cols_present:
        all_flat = True
        for col in numeric_cols_present:
            idx = columns.index(col)
            vals = []
            for r in rows[:200]:
                v = r[idx] if idx < len(r) else None
                if v is not None:
                    try:
                        vals.append(float(v))
                    except (TypeError, ValueError):
                        pass
            if not vals:
                continue
            unique_vals = set(vals)
            # Skip columns whose only values are 0 and/or 1 — these are boolean flags,
            # not financial metrics. They should not prevent the all-flat table routing.
            if unique_vals.issubset({0.0, 1.0}):
                continue
            if len(unique_vals) > 1:
                all_flat = False
                break
        if all_flat:
            return "table"

    return chart_type


def _validate_spec(spec: dict, chart_type: str) -> bool:
    """Return True only if the spec is structurally renderable by vega-embed.

    Returns False for specs that would crash the frontend (missing mark, wrong
    encoding structure, empty kpi values). Does NOT validate data content.
    """
    if not spec:
        return False
    if spec.get("type") == "kpi_card":
        return bool(spec.get("values"))
    if not spec.get("$schema"):
        return False
    # dual_axis uses a layered spec — no top-level mark, validate layers instead
    if chart_type == "dual_axis":
        layers = spec.get("layer")
        return isinstance(layers, list) and len(layers) >= 2
    if not spec.get("mark"):
        return False
    enc = spec.get("encoding") or {}
    if chart_type in ("line", "area", "multi_line", "stacked_area"):
        x_type = (enc.get("x") or {}).get("type")
        if x_type != "temporal":
            return False
    if chart_type in ("pie", "donut"):
        return bool(enc.get("theta"))
    if chart_type not in ("pie", "donut", "kpi_card", "heatmap"):
        if not enc.get("x") or not enc.get("y"):
            return False
    return True


_WATERFALL_MAX_ROWS = 20   # waterfall is meaningless beyond this — window accumulates all rows

def _apply_guardrails(chart_type: str, columns: list[str], col_type_map: dict, n_rows: int = 0) -> str:
    """Minimal structural guardrails — only overrides structurally impossible chart types."""
    if chart_type not in _VALID_CHART_TYPES:
        return "bar"
    n_date = sum(1 for c in columns if col_type_map.get(c) == "date")
    if chart_type in ("line", "area", "multi_line", "stacked_area") and n_date == 0:
        return "bar"
    # Waterfall uses a Vega-Lite window (cumulative sum) over ALL rows in row order.
    # With many rows the cumulative total becomes meaningless — degrade to bar.
    if chart_type == "waterfall" and n_rows > _WATERFALL_MAX_ROWS:
        return "bar"
    return chart_type


async def _plan_chart(
    columns: list[str],
    rows: list[list],
    query_summary: dict,
    state: AnalyticsState,
    config: RunnableConfig,
    intent: str,
    persona: str,
) -> tuple[dict, str]:
    """Call 1 of 2: analytical pass — picks chart type, column bindings, per-axis formats."""
    data_profile = _build_data_profile(columns, rows, query_summary)
    column_metadata = _build_column_metadata(columns, state)

    fb = state.get("feedback_context") or ""
    feedback_section = (
        f"USER CHART PREFERENCES (apply silently):\n<feedback_context>{fb}</feedback_context>"
        if fb else ""
    )

    prompt = CHART_PLAN_PROMPT.format_messages(
        question=state.get("effective_question") or state["question"],
        intent=intent,
        data_profile=data_profile,
        column_metadata=column_metadata,
        feedback_section=feedback_section,
        reasoning_directive=REASONING_DIRECTIVE_NORMAL,
    )

    from app.services.agents.bedrock import get_llm
    from app.core.circuit_breaker import llm_breaker

    llm = get_llm("fast")

    @llm_breaker
    async def _call():
        from app.core.retry import retry_async
        return await retry_async(lambda: llm.ainvoke(prompt, config=config), service="bedrock-chart-planner", max_attempts=2, backoff_base=5.0)

    fallback_type = _fallback_chart_type(columns, rows, intent, persona)
    fallback_plan: dict = {
        "chart_type": fallback_type,
        "x_column": None, "y_column": None, "color_column": None, "size_column": None,
        "x_value_format": None, "y_value_format": ",.0f",
        "color_scheme": "blues", "chart_confidence": 100, "alternative_types": [],
    }

    try:
        response = await _call()
        raw = response.content or ""
        output = parse_tag(raw, "chart")
        if output:
            from json_repair import loads as json_loads
            parsed = json_loads(output)
            if isinstance(parsed, dict):
                for key in ("x_value_format", "y_value_format"):
                    if isinstance(parsed.get(key), str):
                        parsed[key] = parsed[key].replace("~", "")
                return parsed, column_metadata
    except Exception as e:
        logger.warning("chart_agent | plan LLM failed | error={}", e)

    return fallback_plan, column_metadata


async def _label_chart(
    plan: dict,
    col_meta_str: str,
    columns: list[str],
    rows: list[list],
    state: AnalyticsState,
    config: RunnableConfig,
    intent: str,
    persona: str,
) -> dict:
    """Call 2 of 2: presentational pass — writes axis labels, title, legend from the plan."""
    chart_type  = plan.get("chart_type", "bar")
    x_column    = plan.get("x_column") or ""
    y_column    = plan.get("y_column") or ""
    color_column = plan.get("color_column") or ""
    y_value_format = plan.get("y_value_format") or ",.0f"
    alternatives = plan.get("alternative_types") or []

    def _meta_snippet(col_name: str) -> str:
        if not col_name:
            return "(none)"
        for line in col_meta_str.splitlines():
            stripped = line.strip()
            if stripped.startswith(col_name + " ") or stripped.startswith(col_name + "\t"):
                return stripped
        return f"{col_name}  (no catalog entry)"

    def _color_top_values() -> str:
        if not color_column or color_column not in columns:
            return "(none)"
        idx = columns.index(color_column)
        from collections import Counter
        vals = [str(r[idx]) for r in rows if idx < len(r) and r[idx] is not None]
        top = Counter(vals).most_common(5)
        return ", ".join(f'"{v}"' for v, _ in top) if top else "(none)"

    def _fmt_alternatives() -> str:
        if not alternatives:
            return "  (none)"
        parts = []
        for alt in alternatives:
            if isinstance(alt, dict):
                t = alt.get("type", "?")
                xc = alt.get("x_column", "?")
                yc = alt.get("y_column", "?")
                cc = alt.get("color_column")
                line = f'  - {t}: x_column="{xc}", y_column="{yc}"'
                if cc:
                    line += f', color_column="{cc}"'
                parts.append(line)
            else:
                parts.append(f"  - {alt}")
        return "\n".join(parts)

    prompt = CHART_LABEL_PROMPT.format_messages(
        question=state.get("effective_question") or state["question"],
        intent=intent,
        chart_type=chart_type,
        x_column=x_column or "(none)",
        x_column_meta=_meta_snippet(x_column),
        y_column=y_column or "(none)",
        y_column_meta=_meta_snippet(y_column),
        color_column=color_column or "(none)",
        color_top_values=_color_top_values(),
        y_value_format=y_value_format,
        alternatives=_fmt_alternatives(),
        reasoning_directive=REASONING_DIRECTIVE_NORMAL,
    )

    from app.services.agents.bedrock import get_llm
    from app.core.circuit_breaker import llm_breaker

    llm = get_llm("fast")

    @llm_breaker
    async def _call():
        from app.core.retry import retry_async
        return await retry_async(lambda: llm.ainvoke(prompt, config=config), service="bedrock-chart-labeler", max_attempts=2, backoff_base=5.0)

    fallback_labels = {
        "chart_title": _snake_to_title(state["question"][:60]),
        "x_axis_label": _snake_to_title(x_column),
        "y_axis_label": _snake_to_title(y_column),
        "legend_title": _snake_to_title(color_column) if color_column else "",
        "legend_labels": {},
        "alternative_labels": {},
    }

    try:
        response = await _call()
        raw = response.content or ""
        output = parse_tag(raw, "chart")
        if output:
            from json_repair import loads as json_loads
            parsed = json_loads(output)
            if isinstance(parsed, dict):
                return parsed
    except Exception as e:
        logger.warning("chart_agent | label LLM failed | error={}", e)

    return fallback_labels


async def _select_chart_and_labels(
    columns: list[str],
    rows: list[list],
    query_summary: dict,
    state: AnalyticsState,
    config: RunnableConfig,
    intent: str,
    persona: str,
) -> tuple[str, dict]:
    plan, col_meta_str = await _plan_chart(columns, rows, query_summary, state, config, intent, persona)

    # Resolve column hints before calling the labeler so it always gets concrete names.
    # 3-tier: exact → case-insensitive → fuzzy (difflib ≥0.85) → positional fallback.
    import difflib
    ctm_r = _build_col_type_map(columns, rows)
    numeric_r = [c for c in columns if ctm_r.get(c) == "numeric"]
    string_r  = [c for c in columns if ctm_r.get(c) == "string"]
    date_r    = [c for c in columns if ctm_r.get(c) == "date"]
    lower_map = {c.lower(): c for c in columns}

    def _resolve_loose(hint: str | None, fallback) -> str | None:
        if not hint:
            return fallback
        if hint in columns:
            return hint
        if hint.lower() in lower_map:
            return lower_map[hint.lower()]
        m = difflib.get_close_matches(hint.lower(), list(lower_map.keys()), n=1, cutoff=0.85)
        return lower_map[m[0]] if m else fallback

    chart_type = plan.get("chart_type") or _fallback_chart_type(columns, rows, intent, persona)

    if chart_type == "bar_horizontal":
        x_fb = (numeric_r or columns or [None])[0]
        y_fb = (string_r or date_r or columns or [None])[0]
    elif chart_type in ("scatter", "bubble"):
        x_fb = (numeric_r or columns or [None])[0]
        y_fb = numeric_r[1] if len(numeric_r) > 1 else (numeric_r or columns or [None])[-1]
    elif chart_type in ("heatmap",):
        x_fb = (string_r or date_r or columns or [None])[0]
        y_fb = string_r[1] if len(string_r) > 1 else (string_r or columns or [None])[0]
    else:
        x_fb = (date_r or string_r or columns or [None])[0]
        y_fb = (numeric_r or columns or [None])[-1]

    plan["x_column"]     = _resolve_loose(plan.get("x_column"), x_fb)
    plan["y_column"]     = _resolve_loose(plan.get("y_column"), y_fb)
    plan["color_column"] = _resolve_loose(plan.get("color_column"), None)

    label_output = await _label_chart(plan, col_meta_str, columns, rows, state, config, intent, persona)
    labels = {**plan, **label_output}

    _CONFIDENCE_THRESHOLD = 60
    confidence = int(plan.get("chart_confidence", 100))
    if confidence < _CONFIDENCE_THRESHOLD:
        logger.info(
            "chart_agent | low confidence ({}) → falling back to table | thread={}",
            confidence, state.get("thread_id"),
        )
        return "table", labels

    return chart_type, labels


def _fallback_chart_type(columns: list[str], rows: list[list], intent: str, persona: str) -> str:
    """Simple deterministic fallback used only when LLM call fails."""
    import pandas as pd

    if not rows or not columns:
        return "table"
    n_rows = len(rows)
    df = pd.DataFrame(rows, columns=columns)
    n_numeric = sum(1 for c in columns if pd.api.types.is_numeric_dtype(df[c]))
    n_date = sum(
        1 for c in columns
        if df[c].dtype == object and not df[c].dropna().empty
        and df[c].dropna().astype(str).str.match(r"\d{4}-\d{2}-\d{2}").any()
    )
    n_string = sum(1 for c in columns if df[c].dtype == object) - n_date

    if n_rows == 1 and n_numeric >= 1:
        return "kpi_card"
    if n_rows <= 5 and n_numeric == len(columns):
        return "kpi_card"
    if n_date >= 1:
        return "area" if persona in ("executive", "director") else "line"
    if n_string == 1 and n_numeric == 1:
        return "bar" if n_rows > 5 else ("donut" if persona in ("executive", "director") else "pie")
    return "bar"


def _safe_value_format(fmt: str, rows: list[list], col_idx: int) -> str:
    """Guard against .1% being applied to pre-converted percentage values.
    Vega-Lite .1% multiplies by 100 — correct only for ratios between 0 and 1.
    If values are in range 1–100 (already-converted %) → use ,.1f (e.g. 9.4 shows as "9.4").
    If values are > 100 (dollar amounts, counts) → use ,.0f.
    """
    fmt = fmt.replace("~", "")  # strip d3 trim-zeros flag — not supported in all Vega environments
    if "%" not in fmt:
        return fmt
    try:
        sample = [float(rows[j][col_idx]) for j in range(min(10, len(rows))) if rows[j][col_idx] is not None]
        if sample:
            mx = max(abs(v) for v in sample)
            if mx > 100:
                return ",.0f"
            if mx > 1:
                return ",.1f"
    except (TypeError, ValueError, IndexError):
        pass
    return fmt


_FONT = "Inter, sans-serif"

_BASE_CONFIG = {
    "axis":   {"labelFont": _FONT, "titleFont": _FONT, "labelFontSize": 11, "titleFontSize": 11},
    "legend": {"labelFont": _FONT, "titleFont": _FONT, "labelFontSize": 11},
    "title":  {"font": _FONT, "fontSize": 13, "fontWeight": 500},
    "bar":    {"strokeWidth": 0, "cornerRadiusTopLeft": 2, "cornerRadiusTopRight": 2},
    "arc":    {"strokeWidth": 1, "stroke": "white"},
    "line":   {"strokeWidth": 2},
    "area":   {"strokeWidth": 0, "fillOpacity": 0.75},
    "point":  {"strokeWidth": 0, "size": 60},
}


def _build_vega_lite_spec(
    chart_type: str,
    columns: list[str],
    rows: list[list],
    labels: dict,
    col_type_map: dict | None = None,
) -> dict:
    ctm = col_type_map or {}
    numeric_cols = [c for c in columns if ctm.get(c) == "numeric"]
    string_cols  = [c for c in columns if ctm.get(c) == "string"]
    date_cols    = [c for c in columns if ctm.get(c) == "date"]

    def _num(exclude: str | None = None) -> str:
        return next((c for c in numeric_cols if c != exclude),
                    numeric_cols[0] if numeric_cols else columns[-1] if columns else "value")

    def _str(exclude: str | None = None) -> str:
        return next((c for c in string_cols if c != exclude),
                    string_cols[0] if string_cols else columns[0] if columns else "category")

    def _date() -> str:
        return date_cols[0] if date_cols else (columns[0] if columns else "date")

    val_fmt = labels.get("value_format", ",.0f")
    y_title = labels.get("y_axis_label", "")
    x_title = labels.get("x_axis_label", "")

    # ── Hint resolution: 3-tier (exact → case-insensitive → fuzzy ≥0.85) ──────
    import difflib as _difflib
    _lower_col_map = {c.lower(): c for c in columns}

    def _resolve_hint(hint: str | None) -> str | None:
        """Return validated column name or None (caller uses positional fallback)."""
        if not hint:
            return None
        if hint in columns:
            return hint
        if hint.lower() in _lower_col_map:
            return _lower_col_map[hint.lower()]
        m = _difflib.get_close_matches(hint.lower(), list(_lower_col_map.keys()), n=1, cutoff=0.85)
        return _lower_col_map[m[0]] if m else None

    # Raw resolved names (type constraints applied per-chart-type below)
    _xh = _resolve_hint(labels.get("x_column"))
    _yh = _resolve_hint(labels.get("y_column"))
    _ch = _resolve_hint(labels.get("color_column"))
    _sh = _resolve_hint(labels.get("size_column"))

    # Per-axis formats: use dedicated per-axis field, fall back to legacy global value_format
    y_val_fmt = labels.get("y_value_format") or labels.get("value_format", ",.0f")
    x_val_fmt = labels.get("x_value_format") or labels.get("value_format", ",.0f")
    val_fmt = y_val_fmt  # alias — most chart types only have one quantitative axis

    base = {
        "$schema": "https://vega.github.io/schema/vega-lite/v6.json",
        "width": "container",
        "height": 350,
        "background": "transparent",
        "title": labels.get("chart_title", ""),
        "data": {"values": [dict(zip(columns, row)) for row in rows[:500]]},
    }

    # ── KPI card (not a Vega spec — frontend renders it directly) ──────────────
    if chart_type == "kpi_card":
        base["type"] = "kpi_card"
        base["values"] = [dict(zip(columns, row)) for row in rows[:3]]
        return base

    # ── Vertical bar ───────────────────────────────────────────────────────────
    if chart_type == "bar":
        _MAX_BAR_CATS = 25
        bar_rows = rows[:_MAX_BAR_CATS] if len(rows) > _MAX_BAR_CATS else rows
        bar_title = labels.get("chart_title", "")
        if len(rows) > _MAX_BAR_CATS:
            bar_title = f"{bar_title} (top {_MAX_BAR_CATS})" if bar_title else f"Top {_MAX_BAR_CATS}"
        bar_base = {**base,
            "title": bar_title,
            "data": {"values": [dict(zip(columns, row)) for row in bar_rows]},
        }
        y_col = (_yh if _yh and ctm.get(_yh) == "numeric" else None) or _num()
        # When no string col exists (e.g. snapshot date + N numerics), fold numeric
        # columns into metric/value pairs so each metric becomes a bar.
        if not string_cols and numeric_cols:
            fold_cols = numeric_cols
            safe_fmt = _safe_value_format(val_fmt, bar_rows, columns.index(fold_cols[0]) if fold_cols[0] in columns else 0)
            spec = {**bar_base,
                "transform": [{"fold": fold_cols, "as": ["_metric", "_value"]}],
                "mark": "bar",
                "encoding": {
                    "x": {"field": "_metric", "type": "nominal", "sort": None,
                          "axis": {"title": x_title or "Metric", "labelAngle": -30}},
                    "y": {"field": "_value", "type": "quantitative",
                          "axis": {"title": y_title or "Value", "format": safe_fmt}},
                    "color": {"field": "_metric", "type": "nominal"},
                    "tooltip": [
                        {"field": "_metric", "type": "nominal", "title": "Metric"},
                        {"field": "_value", "type": "quantitative", "format": safe_fmt, "title": "Value"},
                    ],
                },
            }
        else:
            x_col = (_xh if _xh and _xh != y_col and ctm.get(_xh) in ("string", "date")
                     else None) or _str(exclude=y_col)
            safe_fmt = _safe_value_format(val_fmt, bar_rows, columns.index(y_col) if y_col in columns else -1)
            has_neg = any(
                i < len(r) and r[i] is not None and float(r[i]) < 0
                for r in bar_rows[:50]
                for i in [columns.index(y_col)] if y_col in columns
            )
            color_enc: dict = (
                {"condition": {"test": f"datum['{y_col}'] < 0", "value": "#e45755"}, "value": "#4c78a8"}
                if has_neg else {}
            )
            enc: dict = {
                "x": {"field": x_col, "type": "nominal", "sort": "-y",
                      "axis": {"title": x_title or x_col, "labelAngle": -45, "labelLimit": 100}},
                "y": {"field": y_col, "type": "quantitative",
                      "axis": {"title": y_title or y_col, "format": safe_fmt}},
            }
            if color_enc:
                enc["color"] = color_enc
            else:
                # Use hint or second string col as color dimension (≤ 20 distinct values).
                color_col = (_ch if _ch and _ch != x_col and _ch != y_col and ctm.get(_ch) == "string"
                             else None) or next((c for c in string_cols if c != x_col), None)
                if color_col and color_col in columns:
                    n_unique = len({str(r[columns.index(color_col)]) for r in bar_rows if columns.index(color_col) < len(r)})
                    if 1 < n_unique <= 20:
                        enc["color"] = {"field": color_col, "type": "nominal"}
            enc["tooltip"] = [
                {"field": x_col, "type": "nominal"},
                {"field": y_col, "type": "quantitative", "format": safe_fmt},
            ]
            spec = {**bar_base, "mark": "bar", "encoding": enc}
        spec["config"] = _BASE_CONFIG
        return spec

    # ── Horizontal bar ─────────────────────────────────────────────────────────
    if chart_type == "bar_horizontal":
        _MAX_HORIZ_CATS = 30
        horiz_rows = rows[:_MAX_HORIZ_CATS] if len(rows) > _MAX_HORIZ_CATS else rows
        horiz_title = labels.get("chart_title", "")
        if len(rows) > _MAX_HORIZ_CATS:
            horiz_title = f"{horiz_title} (top {_MAX_HORIZ_CATS})" if horiz_title else f"Top {_MAX_HORIZ_CATS}"
        horiz_base = {**base,
            "title": horiz_title,
            "data": {"values": [dict(zip(columns, row)) for row in horiz_rows]},
        }
        x_col = (_xh if _xh and ctm.get(_xh) == "numeric" else None) or _num()
        y_col = (_yh if _yh and _yh != x_col and ctm.get(_yh) in ("string", "date")
                 else None) or _str(exclude=x_col)
        safe_fmt = _safe_value_format(x_val_fmt, horiz_rows, columns.index(x_col) if x_col in columns else -1)
        has_neg = any(
            i < len(r) and r[i] is not None and float(r[i]) < 0
            for r in horiz_rows[:50]
            for i in [columns.index(x_col)] if x_col in columns
        )
        color_enc = (
            {"condition": {"test": f"datum['{x_col}'] < 0", "value": "#e45755"}, "value": "#4c78a8"}
            if has_neg else {}
        )
        enc = {
            "y": {"field": y_col, "type": "nominal", "sort": "-x",
                  "axis": {"title": y_title or y_col, "labelLimit": 200}},
            "x": {"field": x_col, "type": "quantitative",
                  "axis": {"title": x_title or x_col, "format": safe_fmt}},
        }
        if color_enc:
            enc["color"] = color_enc
        else:
            color_col = next((c for c in string_cols if c != y_col), None)
            if color_col and color_col in columns:
                n_unique = len({str(r[columns.index(color_col)]) for r in horiz_rows if columns.index(color_col) < len(r)})
                if 1 < n_unique <= 20:
                    enc["color"] = {"field": color_col, "type": "nominal"}
        enc["tooltip"] = [
            {"field": y_col, "type": "nominal"},
            {"field": x_col, "type": "quantitative", "format": safe_fmt},
        ]
        spec = {**horiz_base, "mark": "bar", "encoding": enc, "config": _BASE_CONFIG}
        return spec

    # ── Line / Area ────────────────────────────────────────────────────────────
    if chart_type in ("line", "area"):
        x_col = (_xh if _xh and ctm.get(_xh) == "date" else None) or _date()
        y_col = (_yh if _yh and ctm.get(_yh) == "numeric" and _yh != x_col else None) or _num(exclude=x_col)
        # Add color dimension if a string column exists (single-series line per entity)
        cat_col = (_ch if _ch and _ch != x_col and _ch != y_col and ctm.get(_ch) == "string"
                   else None) or (string_cols[0] if string_cols else None)
        enc = {
            "x": {"field": x_col, "type": "temporal", "timeUnit": "yearmonthdate",
                  "axis": {"title": x_title or "Date", "format": "%b %d, %Y"}},
            "y": {"field": y_col, "type": "quantitative",
                  "axis": {"title": y_title or y_col, "format": val_fmt}},
        }
        if cat_col:
            enc["color"] = {"field": cat_col, "type": "nominal"}
        enc["tooltip"] = [
            {"field": x_col, "type": "temporal", "timeUnit": "yearmonthdate", "format": "%b %d, %Y", "title": "Date"},
            {"field": y_col, "type": "quantitative", "format": val_fmt},
        ]
        if cat_col:
            enc["tooltip"].append({"field": cat_col, "type": "nominal"})
        mark: dict | str = {"type": chart_type, "point": True} if chart_type == "line" else chart_type
        spec = {**base, "mark": mark, "encoding": enc, "config": _BASE_CONFIG}
        return spec

    # ── Multi-line / Stacked area ──────────────────────────────────────────────
    if chart_type in ("multi_line", "stacked_area"):
        x_col = (_xh if _xh and ctm.get(_xh) == "date" else None) or _date()
        mark_type = "line" if chart_type == "multi_line" else "area"

        if string_cols:
            # Category column drives color — one line/area per category value
            cat_col = (_ch if _ch and _ch != x_col and ctm.get(_ch) == "string"
                       else None) or _str(exclude=x_col)
            y_col   = (_yh if _yh and ctm.get(_yh) == "numeric" and _yh != x_col
                       else None) or _num(exclude=x_col)
            enc = {
                "x": {"field": x_col, "type": "temporal", "timeUnit": "yearmonthdate",
                      "axis": {"title": x_title or "Date", "format": "%b %d, %Y"}},
                "y": {"field": y_col, "type": "quantitative",
                      "axis": {"title": y_title or y_col, "format": val_fmt}},
                "color": {"field": cat_col, "type": "nominal"},
            }
            if chart_type == "stacked_area":
                enc["y"]["stack"] = "zero"
            enc["tooltip"] = [
                {"field": x_col, "type": "temporal", "timeUnit": "yearmonthdate", "format": "%b %d, %Y", "title": "Date"},
                {"field": y_col, "type": "quantitative", "format": val_fmt},
                {"field": cat_col, "type": "nominal"},
            ]
            mark_spec: dict | str = {"type": "line", "point": True} if chart_type == "multi_line" else "area"
            spec = {**base, "mark": mark_spec, "encoding": enc, "config": _BASE_CONFIG}
        else:
            # No string column — fold multiple numeric columns into series
            # e.g. (date, usd_balance, eur_balance, gbp_balance) → 3 lines
            series_cols = [c for c in numeric_cols if c != x_col]
            if not series_cols:
                series_cols = numeric_cols[:1]
            enc = {
                "x": {"field": x_col, "type": "temporal", "timeUnit": "yearmonthdate",
                      "axis": {"title": x_title or "Date", "format": "%b %d, %Y"}},
                "y": {"field": "_value", "type": "quantitative",
                      "axis": {"title": y_title or "Value", "format": val_fmt}},
                "color": {"field": "_series", "type": "nominal"},
                "tooltip": [
                    {"field": x_col, "type": "temporal", "timeUnit": "yearmonthdate", "format": "%b %d, %Y", "title": "Date"},
                    {"field": "_value", "type": "quantitative", "format": val_fmt, "title": "Value"},
                    {"field": "_series", "type": "nominal", "title": "Series"},
                ],
            }
            if chart_type == "stacked_area":
                enc["y"]["stack"] = "zero"
            fold_mark: dict | str = {"type": "line", "point": True} if chart_type == "multi_line" else "area"
            spec = {
                **base,
                "transform": [{"fold": series_cols, "as": ["_series", "_value"]}],
                "mark": fold_mark,
                "encoding": enc,
                "config": _BASE_CONFIG,
            }
        return spec

    # ── Pie / Donut ────────────────────────────────────────────────────────────
    if chart_type in ("pie", "donut"):
        name_col  = (_xh if _xh and ctm.get(_xh) == "string" else None) or _str()
        value_col = (_yh if _yh and ctm.get(_yh) == "numeric" else None) or _num()
        inner = 65 if chart_type == "donut" else 0
        spec = {
            **base,
            "mark": {"type": "arc", "innerRadius": inner, "padAngle": 0.015, "cornerRadius": 3},
            "encoding": {
                "theta": {"field": value_col, "type": "quantitative", "stack": True},
                "color": {"field": name_col,  "type": "nominal"},
                "tooltip": [
                    {"field": name_col,  "type": "nominal",     "title": name_col},
                    {"field": value_col, "type": "quantitative", "title": value_col, "format": val_fmt},
                ],
            },
            "config": _BASE_CONFIG,
        }
        return spec

    # ── Grouped bar / Stacked bar ──────────────────────────────────────────────
    if chart_type in ("grouped_bar", "stacked_bar"):
        y_col   = (_yh if _yh and ctm.get(_yh) == "numeric" else None) or _num()
        x_col   = (_xh if _xh and ctm.get(_xh) in ("string", "date") and _xh != y_col
                   else None) or (string_cols[0] if string_cols else (date_cols[0] if date_cols else columns[0]))
        cat_col = (_ch if _ch and _ch != x_col and _ch != y_col and ctm.get(_ch) == "string"
                   else None) or (
                      next((c for c in string_cols if c != x_col), None)
                      or (string_cols[0] if string_cols else columns[0])
                  )
        x_type  = "temporal" if x_col in date_cols else "nominal"
        safe_fmt = _safe_value_format(val_fmt, rows, columns.index(y_col) if y_col in columns else -1)
        enc = {
            "x": {"field": x_col, "type": x_type,
                  "axis": {"title": x_title or x_col, "labelAngle": -30}},
            "y": {"field": y_col, "type": "quantitative",
                  "axis": {"title": y_title or y_col, "format": safe_fmt}},
            "color": {"field": cat_col, "type": "nominal"},
        }
        if chart_type == "stacked_bar":
            enc["y"]["stack"] = "zero"
        else:
            enc["xOffset"] = {"field": cat_col}
        enc["tooltip"] = [
            {"field": x_col, "type": x_type},
            {"field": y_col, "type": "quantitative", "format": safe_fmt},
            {"field": cat_col, "type": "nominal"},
        ]
        spec = {**base, "mark": "bar", "encoding": enc, "config": _BASE_CONFIG}
        return spec

    # ── Scatter ────────────────────────────────────────────────────────────────
    if chart_type == "scatter":
        x_col   = (_xh if _xh and ctm.get(_xh) == "numeric" else None) or _num()
        y_col   = (_yh if _yh and ctm.get(_yh) == "numeric" and _yh != x_col else None) or _num(exclude=x_col)
        cat_col = (_ch if _ch and _ch != x_col and _ch != y_col and ctm.get(_ch) == "string"
                   else None) or (string_cols[0] if string_cols else None)
        safe_x_fmt = _safe_value_format(x_val_fmt, rows, columns.index(x_col) if x_col in columns else -1)
        safe_y_fmt = _safe_value_format(y_val_fmt, rows, columns.index(y_col) if y_col in columns else -1)
        enc = {
            "x": {"field": x_col, "type": "quantitative",
                  "axis": {"title": x_title or x_col, "format": safe_x_fmt}},
            "y": {"field": y_col, "type": "quantitative",
                  "axis": {"title": y_title or y_col, "format": safe_y_fmt}},
            "tooltip": [
                {"field": x_col, "type": "quantitative", "format": safe_x_fmt},
                {"field": y_col, "type": "quantitative", "format": safe_y_fmt},
            ],
        }
        if cat_col:
            enc["color"] = {"field": cat_col, "type": "nominal"}
            enc["tooltip"].append({"field": cat_col, "type": "nominal"})  # type: ignore[attr-defined]
        spec = {**base, "mark": {"type": "point", "filled": True}, "encoding": enc, "config": _BASE_CONFIG}
        return spec

    # ── Bubble ─────────────────────────────────────────────────────────────────
    if chart_type == "bubble":
        x_col    = (_xh if _xh and ctm.get(_xh) == "numeric" else None) or (numeric_cols[0] if numeric_cols else columns[0])
        y_col    = (_yh if _yh and ctm.get(_yh) == "numeric" and _yh != x_col else None) or (numeric_cols[1] if len(numeric_cols) >= 2 else x_col)
        size_col = (_sh if _sh and ctm.get(_sh) == "numeric" and _sh not in (x_col, y_col) else None) or (numeric_cols[2] if len(numeric_cols) >= 3 else y_col)
        cat_col  = (_ch if _ch and _ch not in (x_col, y_col, size_col) and ctm.get(_ch) == "string"
                    else None) or (string_cols[0] if string_cols else None)
        safe_x_fmt = _safe_value_format(x_val_fmt, rows, columns.index(x_col) if x_col in columns else -1)
        safe_y_fmt = _safe_value_format(y_val_fmt, rows, columns.index(y_col) if y_col in columns else -1)
        enc = {
            "x":    {"field": x_col,    "type": "quantitative", "axis": {"title": x_title or x_col, "format": safe_x_fmt}},
            "y":    {"field": y_col,    "type": "quantitative", "axis": {"title": y_title or y_col, "format": safe_y_fmt}},
            "size": {"field": size_col, "type": "quantitative"},
        }
        if cat_col:
            enc["color"] = {"field": cat_col, "type": "nominal"}
        enc["tooltip"] = [
            {"field": x_col, "type": "quantitative", "format": safe_x_fmt},
            {"field": y_col, "type": "quantitative", "format": safe_y_fmt},
            {"field": size_col, "type": "quantitative"},
        ]
        if cat_col:
            enc["tooltip"].append({"field": cat_col, "type": "nominal"})
        spec = {**base, "mark": {"type": "point", "filled": True, "opacity": 0.7},
                "encoding": enc, "config": _BASE_CONFIG}
        return spec

    # ── Heatmap ────────────────────────────────────────────────────────────────
    if chart_type == "heatmap":
        x_col   = (_xh if _xh and ctm.get(_xh) in ("string", "date") else None) or (string_cols[0] if string_cols else (date_cols[0] if date_cols else columns[0]))
        y_col   = (_yh if _yh and ctm.get(_yh) == "string" and _yh != x_col else None) or (string_cols[1] if len(string_cols) > 1 else (string_cols[0] if string_cols else columns[0]))
        val_col = _num()
        x_type  = "temporal" if x_col in date_cols else "nominal"
        spec = {
            **base,
            "mark": {"type": "rect"},
            "encoding": {
                "x":     {"field": x_col,   "type": x_type,        "axis": {"title": x_title or x_col}},
                "y":     {"field": y_col,   "type": "nominal",     "axis": {"title": y_title or y_col}},
                "color": {"field": val_col, "type": "quantitative", "scale": {"scheme": "blues"},
                          "legend": {"title": val_col, "format": val_fmt}},
                "tooltip": [
                    {"field": x_col,   "type": x_type},
                    {"field": y_col,   "type": "nominal"},
                    {"field": val_col, "type": "quantitative", "format": val_fmt},
                ],
            },
            "config": _BASE_CONFIG,
        }
        return spec

    # ── Waterfall (cash flow bridge / P&L attribution) ─────────────────────────
    # Waterfall uses a Vega-Lite window (cumulative sum) over all data rows.
    # Each row = one discrete contribution; the window stacks them left→right.
    # For this to be legible: cap at _WATERFALL_MAX_ROWS and deduplicate by x_col
    # (if multiple rows share the same label, pre-aggregate them here in Python
    # so the window doesn't double-count).
    if chart_type == "waterfall":
        x_col = (_xh if _xh and ctm.get(_xh) in ("string", "date") else None) or _str()
        y_col = (_yh if _yh and ctm.get(_yh) == "numeric" and _yh != x_col else None) or _num()

        # Pre-aggregate: collapse rows sharing the same x_col value.
        # Without this, a label like "CASH_LIQUIDITY" appearing 30 times produces
        # a 30-step cumulative window — visually it looks like a single enormous bar.
        if x_col in columns and y_col in columns:
            xi = columns.index(x_col)
            yi = columns.index(y_col)
            agg: dict = {}
            for r in rows:
                xv = str(r[xi]) if xi < len(r) else ""
                try:
                    yv = float(r[yi]) if yi < len(r) and r[yi] is not None else 0.0
                except (TypeError, ValueError):
                    yv = 0.0
                agg[xv] = agg.get(xv, 0.0) + yv
            # Sort descending by absolute value so largest steps come first
            wf_rows = sorted(
                [[k, v] for k, v in agg.items()],
                key=lambda r: abs(r[1]),
                reverse=True,
            )[:_WATERFALL_MAX_ROWS]
            wf_columns = [x_col, y_col]
        else:
            wf_rows = rows[:_WATERFALL_MAX_ROWS]
            wf_columns = columns

        safe_fmt = _safe_value_format(val_fmt, wf_rows, 1)
        wf_base = {**base,
            "data": {"values": [dict(zip(wf_columns, r)) for r in wf_rows]},
        }
        spec = {
            **wf_base,
            "mark": {"type": "bar", "cornerRadiusTopLeft": 2, "cornerRadiusTopRight": 2},
            "transform": [
                {"window": [{"op": "sum", "field": y_col, "as": "_wf_sum"}], "frame": [None, 0]},
                {"calculate": f"datum._wf_sum - datum['{y_col}']", "as": "_wf_prev"},
            ],
            "encoding": {
                "x": {"field": x_col, "type": "nominal", "sort": None,
                      "axis": {"title": x_title or x_col, "labelAngle": -30, "labelLimit": 120}},
                "y":  {"field": "_wf_sum",  "type": "quantitative",
                       "axis": {"title": y_title or y_col, "format": safe_fmt}},
                "y2": {"field": "_wf_prev"},
                "color": {
                    "condition": {"test": f"datum['{y_col}'] < 0", "value": "#e45755"},
                    "value": "#4c78a8",
                },
                "tooltip": [
                    {"field": x_col,       "type": "nominal"},
                    {"field": y_col,       "type": "quantitative", "format": safe_fmt, "title": "Change"},
                    {"field": "_wf_sum",   "type": "quantitative", "format": safe_fmt, "title": "Running Total"},
                ],
            },
            "config": _BASE_CONFIG,
        }
        return spec

    # ── Dual axis (layered: primary line + secondary line on right y-axis) ─────
    if chart_type == "dual_axis":
        x_col  = (_xh if _xh and ctm.get(_xh) in ("date", "string") else None) or (date_cols[0] if date_cols else (string_cols[0] if string_cols else columns[0]))
        x_type = "temporal" if x_col in date_cols else "nominal"
        x_axis_cfg = ({"timeUnit": "yearmonthdate", "axis": {"title": x_title or "Date", "format": "%b %d, %Y"}}
                      if x_type == "temporal" else {"axis": {"title": x_title or x_col}})
        y1_col = (_yh if _yh and ctm.get(_yh) == "numeric" else None) or (numeric_cols[0] if numeric_cols else columns[-1])
        y2_col = numeric_cols[1] if len(numeric_cols) > 1 else y1_col
        y1_fmt = _safe_value_format(val_fmt, rows, columns.index(y1_col) if y1_col in columns else -1)
        spec = {
            **base,
            "layer": [
                {
                    "mark": {"type": "line", "color": "#4c78a8", "strokeWidth": 2,
                             "point": {"filled": True, "color": "#4c78a8", "size": 50}},
                    "encoding": {
                        "x": {"field": x_col, "type": x_type, **x_axis_cfg},
                        "y": {"field": y1_col, "type": "quantitative",
                              "axis": {"title": y1_col, "format": y1_fmt, "titleColor": "#4c78a8"}},
                        "tooltip": [
                            {"field": x_col, "type": x_type, **({"timeUnit": "yearmonthdate", "format": "%b %d, %Y"} if x_type == "temporal" else {})},
                            {"field": y1_col, "type": "quantitative", "format": y1_fmt},
                        ],
                    },
                },
                {
                    "mark": {"type": "line", "color": "#f58518", "strokeWidth": 2,
                             "strokeDash": [4, 2],
                             "point": {"filled": True, "color": "#f58518", "size": 50}},
                    "encoding": {
                        "x": {"field": x_col, "type": x_type},
                        "y": {"field": y2_col, "type": "quantitative",
                              "axis": {"title": y2_col, "orient": "right", "titleColor": "#f58518"}},
                        "tooltip": [
                            {"field": x_col, "type": x_type, **({"timeUnit": "yearmonthdate", "format": "%b %d, %Y"} if x_type == "temporal" else {})},
                            {"field": y2_col, "type": "quantitative"},
                        ],
                    },
                },
            ],
            "resolve": {"scale": {"y": "independent"}},
            "config": _BASE_CONFIG,
        }
        return spec

    # ── Fallback ───────────────────────────────────────────────────────────────
    x_col = string_cols[0] if string_cols else (date_cols[0] if date_cols else columns[0])
    y_col = _num()
    return {
        **base,
        "mark": "bar",
        "encoding": {
            "x": {"field": x_col, "type": "nominal", "sort": "-y"},
            "y": {"field": y_col, "type": "quantitative", "axis": {"format": val_fmt}},
        },
        "config": _BASE_CONFIG,
    }


def _build_table_spec(columns: list[str], rows: list[list]) -> dict:
    return {
        "type": "table",
        "columns": columns,
        "rows": [list(r) for r in rows[:200]],
    }


